// GENERATED by scripts/fetch_images.py. Do not edit by hand.
import type { RecipeImageData } from "./types";

export const images: Record<string, RecipeImageData> = {
  "shredded-chicken-street-tacos": {
    "url": "https://images.unsplash.com/photo-1611699363784-f48a38b41a78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaHJlZGRlZCUyMGNoaWNrZW4lMjBzdHJlZXQlMjB0YWNvcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1611699363784-f48a38b41a78?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaHJlZGRlZCUyMGNoaWNrZW4lMjBzdHJlZXQlMjB0YWNvcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0MzZ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f38cc0",
    "alt": "white ceramic plate with food",
    "attribution": {
      "name": "Davey Gravy",
      "username": "davey_gravy",
      "photoLink": "https://unsplash.com/photos/white-ceramic-plate-with-food-J0_WZzGwmrA",
      "userLink": "https://unsplash.com/@davey_gravy"
    }
  },
  "buffalo-chicken-stuffed-sweet-potatoes": {
    "url": "https://images.unsplash.com/photo-1654426939189-9dcf7fed870b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHN0dWZmZWQlMjBzd2VldCUyMHBvdGF0b2VzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQzN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1654426939189-9dcf7fed870b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHN0dWZmZWQlMjBzd2VldCUyMHBvdGF0b2VzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQzN3ww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#594026",
    "alt": "a white plate topped with fried food on top of a table",
    "attribution": {
      "name": "David Trinks",
      "username": "dtrinksrph",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-fried-food-on-top-of-a-table-EuET7ZThg0c",
      "userLink": "https://unsplash.com/@dtrinksrph"
    }
  },
  "chicken-enchilada-skillet": {
    "url": "https://images.unsplash.com/photo-1602536966945-7153f9554a0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwZW5jaGlsYWRhJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1602536966945-7153f9554a0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwZW5jaGlsYWRhJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0Mzh8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c5926",
    "alt": "vegetable salad on black ceramic plate",
    "attribution": {
      "name": "Henryk Sanza",
      "username": "cocovery75",
      "photoLink": "https://unsplash.com/photos/vegetable-salad-on-black-ceramic-plate-vfOqg-HgQ34",
      "userLink": "https://unsplash.com/@cocovery75"
    }
  },
  "beef-barbacoa-tacos": {
    "url": "https://images.unsplash.com/photo-1613514785291-fbd52e18e13f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYmFyYmFjb2ElMjB0YWNvcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1613514785291-fbd52e18e13f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYmFyYmFjb2ElMjB0YWNvcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0Mzl8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c400c",
    "alt": "a plate of food and a bottle of beer on a table",
    "attribution": {
      "name": "Jarritos Mexican Soda",
      "username": "jarritos",
      "photoLink": "https://unsplash.com/photos/a-plate-of-food-and-a-bottle-of-beer-on-a-table-lLEaY8Ehmek",
      "userLink": "https://unsplash.com/@jarritos"
    }
  },
  "bbq-pulled-pork-sandwiches-with-slaw": {
    "url": "https://images.unsplash.com/photo-1565731152987-977b0c939e0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiYnElMjBwdWxsZWQlMjBwb3JrJTIwc2FuZHdpY2hlcyUyMHdpdGglMjBzbGF3JTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1565731152987-977b0c939e0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiYnElMjBwdWxsZWQlMjBwb3JrJTIwc2FuZHdpY2hlcyUyMHdpdGglMjBzbGF3JTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "hamburger with patty",
    "attribution": {
      "name": "Sumaiya Ahmed",
      "username": "sumaiyarecs",
      "photoLink": "https://unsplash.com/photos/hamburger-with-patty-tY312jopFAo",
      "userLink": "https://unsplash.com/@sumaiyarecs"
    }
  },
  "carnitas-bowls": {
    "url": "https://images.unsplash.com/photo-1722239319565-ace2d79a5623?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjYXJuaXRhcyUyMGJvd2xzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1722239319565-ace2d79a5623?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjYXJuaXRhcyUyMGJvd2xzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3730c",
    "alt": "A plate of food on a colorful table cloth",
    "attribution": {
      "name": "Alimentos Fotogénicos",
      "username": "alimentosfotogenicos",
      "photoLink": "https://unsplash.com/photos/a-plate-of-food-on-a-colorful-table-cloth-E2FfSlqVr1U",
      "userLink": "https://unsplash.com/@alimentosfotogenicos"
    }
  },
  "sheet-pan-salmon-with-lemon-asparagus-and-potatoes": {
    "url": "https://images.unsplash.com/photo-1573691843386-8b311aefa811?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMHNhbG1vbiUyMHdpdGglMjBsZW1vbiUyMGFzcGFyYWd1cyUyMGFuZCUyMHBvdGF0b2VzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MXww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1573691843386-8b311aefa811?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMHNhbG1vbiUyMHdpdGglMjBsZW1vbiUyMGFzcGFyYWd1cyUyMGFuZCUyMHBvdGF0b2VzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0MXww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "plate of asparagus beside fork",
    "attribution": {
      "name": "Tim Bish",
      "username": "tjsocoz",
      "photoLink": "https://unsplash.com/photos/plate-of-asparagus-beside-fork-i31hiD8LINA",
      "userLink": "https://unsplash.com/@tjsocoz"
    }
  },
  "sheet-pan-chicken-fajitas": {
    "url": "https://images.unsplash.com/photo-1598515213381-80d77efcdf32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMGNoaWNrZW4lMjBmYWppdGFzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1598515213381-80d77efcdf32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMGNoaWNrZW4lMjBmYWppdGFzJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3Njg4MDQ0Mnww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#a67359",
    "alt": "potato fries on white ceramic bowl",
    "attribution": {
      "name": "Sam Moghadam",
      "username": "sammoghadam",
      "photoLink": "https://unsplash.com/photos/potato-fries-on-white-ceramic-bowl-EaAhF9CZcsY",
      "userLink": "https://unsplash.com/@sammoghadam"
    }
  },
  "greek-chicken-thighs-with-lemon-potatoes": {
    "url": "https://images.unsplash.com/photo-1680098021573-b9402ee336ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMGNoaWNrZW4lMjB0aGlnaHMlMjB3aXRoJTIwbGVtb24lMjBwb3RhdG9lcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1680098021573-b9402ee336ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMGNoaWNrZW4lMjB0aGlnaHMlMjB3aXRoJTIwbGVtb24lMjBwb3RhdG9lcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "two bowls of food with lemons, meat, and vegetables",
    "attribution": {
      "name": "Babs Gorniak",
      "username": "babs_gorniak",
      "photoLink": "https://unsplash.com/photos/two-bowls-of-food-with-lemons-meat-and-vegetables-xgDsiUC5p-w",
      "userLink": "https://unsplash.com/@babs_gorniak"
    }
  },
  "air-fryer-chicken-parmesan": {
    "url": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhaXIlMjBmcnllciUyMGNoaWNrZW4lMjBwYXJtZXNhbiUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhaXIlMjBmcnllciUyMGNoaWNrZW4lMjBwYXJtZXNhbiUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDN8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#a6a6a6",
    "alt": "a plate of food with meat and broccoli",
    "attribution": {
      "name": "Clark Douglas",
      "username": "clark_douglas",
      "photoLink": "https://unsplash.com/photos/a-plate-of-food-with-meat-and-broccoli-HhEfe0DeMiA",
      "userLink": "https://unsplash.com/@clark_douglas"
    }
  },
  "air-fryer-turkey-meatballs-with-pasta": {
    "url": "https://images.unsplash.com/photo-1674456720401-1557c76bf72c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhaXIlMjBmcnllciUyMHR1cmtleSUyMG1lYXRiYWxscyUyMHdpdGglMjBwYXN0YSUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1674456720401-1557c76bf72c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhaXIlMjBmcnllciUyMHR1cmtleSUyMG1lYXRiYWxscyUyMHdpdGglMjBwYXN0YSUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDR8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0a6a6",
    "alt": "a plate of spaghetti with meatballs and sauce",
    "attribution": {
      "name": "Elena Leya",
      "username": "foodistika",
      "photoLink": "https://unsplash.com/photos/a-plate-of-spaghetti-with-meatballs-and-sauce-ptJf7Aqq16I",
      "userLink": "https://unsplash.com/@foodistika"
    }
  },
  "ground-turkey-taco-skillet": {
    "url": "https://images.unsplash.com/photo-1707293672847-ebf417c50bc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncm91bmQlMjB0dXJrZXklMjB0YWNvJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1707293672847-ebf417c50bc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncm91bmQlMjB0dXJrZXklMjB0YWNvJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDR8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "a close up of a plate of food on a table",
    "attribution": {
      "name": "kaori kubota",
      "username": "kuuuudoooo",
      "photoLink": "https://unsplash.com/photos/a-close-up-of-a-plate-of-food-on-a-table-5glmJqknN1Q",
      "userLink": "https://unsplash.com/@kuuuudoooo"
    }
  },
  "shrimp-and-sausage-skillet": {
    "url": "https://images.unsplash.com/photo-1761545832792-535fafbad368?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaHJpbXAlMjBhbmQlMjBzYXVzYWdlJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1761545832792-535fafbad368?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaHJpbXAlMjBhbmQlMjBzYXVzYWdlJTIwc2tpbGxldCUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzY4ODA0NDV8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#738ca6",
    "alt": "Shrimp in sauce with mixed vegetables and limes",
    "attribution": {
      "name": "Zayed Ahmed Zadu",
      "username": "zayed_ahmed_zadu",
      "photoLink": "https://unsplash.com/photos/shrimp-in-sauce-with-mixed-vegetables-and-limes-cujwrR1zfDI",
      "userLink": "https://unsplash.com/@zayed_ahmed_zadu"
    }
  },
  "stuffed-peppers-with-turkey-and-quinoa": {
    "url": "https://images.unsplash.com/photo-1673646960062-9aeb2188335f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzdHVmZmVkJTIwcGVwcGVycyUyMHdpdGglMjB0dXJrZXklMjBhbmQlMjBxdWlub2ElMjBkaW5uZXIlMjBwbGF0ZXxlbnwxfDB8fHwxNzc2ODgwNDQ2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1673646960062-9aeb2188335f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzdHVmZmVkJTIwcGVwcGVycyUyMHdpdGglMjB0dXJrZXklMjBhbmQlMjBxdWlub2ElMjBkaW5uZXIlMjBwbGF0ZXxlbnwxfDB8fHwxNzc2ODgwNDQ2fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#EFEFEF",
    "alt": "a white plate topped with stuffed bell peppers",
    "attribution": {
      "name": "Natalia Gusakova",
      "username": "nataliaraylenegusakova",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-stuffed-bell-peppers-myfDbaJr6vA",
      "userLink": "https://unsplash.com/@nataliaraylenegusakova"
    }
  },
  "chicken-dump-soup": {
    "url": "https://images.unsplash.com/photo-1706740006781-3ca0149307e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwZHVtcCUyMHNvdXAlMjBzb3VwJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDQ3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1706740006781-3ca0149307e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwZHVtcCUyMHNvdXAlMjBzb3VwJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDQ3fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c8c8c",
    "alt": "a bowl of soup with meatballs and vegetables",
    "attribution": {
      "name": "Uehara Photography",
      "username": "ueharaphotography",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-soup-with-meatballs-and-vegetables-gHgwI8X_fl8",
      "userLink": "https://unsplash.com/@ueharaphotography"
    }
  },
  "italian-wedding-soup": {
    "url": "https://images.unsplash.com/photo-1706740006781-3ca0149307e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxpdGFsaWFuJTIwd2VkZGluZyUyMHNvdXAlMjBzb3VwJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDQ3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1706740006781-3ca0149307e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxpdGFsaWFuJTIwd2VkZGluZyUyMHNvdXAlMjBzb3VwJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDQ3fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c8c8c",
    "alt": "a bowl of soup with meatballs and vegetables",
    "attribution": {
      "name": "Uehara Photography",
      "username": "ueharaphotography",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-soup-with-meatballs-and-vegetables-gHgwI8X_fl8",
      "userLink": "https://unsplash.com/@ueharaphotography"
    }
  },
  "red-lentil-soup": {
    "url": "https://images.unsplash.com/photo-1776429054130-480a95531159?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxyZWQlMjBsZW50aWwlMjBzb3VwJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ0OHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1776429054130-480a95531159?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxyZWQlMjBsZW50aWwlMjBzb3VwJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ0OHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "Bowl of tomato soup with fresh herbs and cutlery",
    "attribution": {
      "name": "Theo Lonic",
      "username": "thorai9akira",
      "photoLink": "https://unsplash.com/photos/bowl-of-tomato-soup-with-fresh-herbs-and-cutlery-iVhVUfWvJHc",
      "userLink": "https://unsplash.com/@thorai9akira"
    }
  },
  "white-bean-and-kale-soup-with-sausage": {
    "url": "https://images.unsplash.com/photo-1480522584172-f5845b7b7f4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGJlYW4lMjBhbmQlMjBrYWxlJTIwc291cCUyMHdpdGglMjBzYXVzYWdlJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ0OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1480522584172-f5845b7b7f4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGJlYW4lMjBhbmQlMjBrYWxlJTIwc291cCUyMHdpdGglMjBzYXVzYWdlJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ0OXww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#0c2626",
    "alt": "sliced bread beside porrage",
    "attribution": {
      "name": "Kelly Sikkema",
      "username": "kellysikkema",
      "photoLink": "https://unsplash.com/photos/sliced-bread-beside-porrage-Uk4K9nC_9cA",
      "userLink": "https://unsplash.com/@kellysikkema"
    }
  },
  "beef-and-barley-soup": {
    "url": "https://images.unsplash.com/photo-1666724283335-0532322fccb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYW5kJTIwYmFybGV5JTIwc291cCUyMHNvdXAlMjBib3dsfGVufDF8MHx8fDE3NzY4ODA0NDl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1666724283335-0532322fccb7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYW5kJTIwYmFybGV5JTIwc291cCUyMHNvdXAlMjBib3dsfGVufDF8MHx8fDE3NzY4ODA0NDl8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0c0c0",
    "alt": "a bowl of food",
    "attribution": {
      "name": "Danielle Townsend",
      "username": "danitownzen01",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-food-2uR9V8bTkCg",
      "userLink": "https://unsplash.com/@danitownzen01"
    }
  },
  "chicken-tortilla-soup": {
    "url": "https://images.unsplash.com/photo-1695088224651-162033438b3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwdG9ydGlsbGElMjBzb3VwJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1695088224651-162033438b3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwdG9ydGlsbGElMjBzb3VwJTIwc291cCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1MHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#400c0c",
    "alt": "a bowl of chili sauce with a spoon in it",
    "attribution": {
      "name": "Kelsey Todd",
      "username": "sparkledump",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-chili-sauce-with-a-spoon-in-it-T6D_RDoQ82E",
      "userLink": "https://unsplash.com/@sparkledump"
    }
  },
  "veggie-egg-muffins": {
    "url": "https://images.unsplash.com/photo-1518310532637-f5225f94f3c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx2ZWdnaWUlMjBlZ2clMjBtdWZmaW5zJTIwYnJlYWtmYXN0fGVufDF8MHx8fDE3NzY4ODA0NTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1518310532637-f5225f94f3c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx2ZWdnaWUlMjBlZ2clMjBtdWZmaW5zJTIwYnJlYWtmYXN0fGVufDF8MHx8fDE3NzY4ODA0NTF8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#737373",
    "alt": "grilled patties with tomato toppings",
    "attribution": {
      "name": "Kaitlyn Chow",
      "username": "kaitlynraeann",
      "photoLink": "https://unsplash.com/photos/grilled-patties-with-tomato-toppings-tIElrLKqdjo",
      "userLink": "https://unsplash.com/@kaitlynraeann"
    }
  },
  "protein-overnight-oats": {
    "url": "https://images.unsplash.com/photo-1490371475955-4cb3bfc72f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwb3Zlcm5pZ2h0JTIwb2F0cyUyMGJyZWFrZmFzdHxlbnwxfDB8fHwxNzc2ODgwNDUyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1490371475955-4cb3bfc72f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwb3Zlcm5pZ2h0JTIwb2F0cyUyMGJyZWFrZmFzdHxlbnwxfDB8fHwxNzc2ODgwNDUyfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "granola and yoghurt filled mason jar",
    "attribution": {
      "name": "Alisha Hieb",
      "username": "wildandinlove",
      "photoLink": "https://unsplash.com/photos/granola-and-yoghurt-filled-mason-jar-LzrMzmVWhJw",
      "userLink": "https://unsplash.com/@wildandinlove"
    }
  },
  "greek-yogurt-parfait": {
    "url": "https://images.unsplash.com/photo-1763576178054-ff0152753fd8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMHlvZ3VydCUyMHBhcmZhaXQlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1763576178054-ff0152753fd8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMHlvZ3VydCUyMHBhcmZhaXQlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1Mnww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3c026",
    "alt": "Yogurt cup with granola, banana, and spoon on yellow background",
    "attribution": {
      "name": "Nikita Khowala",
      "username": "nikitakhowala",
      "photoLink": "https://unsplash.com/photos/yogurt-cup-with-granola-banana-and-spoon-on-yellow-background-jxt0SNnrtm0",
      "userLink": "https://unsplash.com/@nikitakhowala"
    }
  },
  "make-ahead-breakfast-burritos": {
    "url": "https://images.unsplash.com/photo-1647545401800-bd8f77e670ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtYWtlLWFoZWFkJTIwYnJlYWtmYXN0JTIwYnVycml0b3MlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1647545401800-bd8f77e670ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtYWtlLWFoZWFkJTIwYnJlYWtmYXN0JTIwYnVycml0b3MlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1M3ww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "a close up of a plate of food on a table",
    "attribution": {
      "name": "Mikey Frost",
      "username": "frostyfilmsandphoto",
      "photoLink": "https://unsplash.com/photos/a-close-up-of-a-plate-of-food-on-a-table-jzaA_v8ucGs",
      "userLink": "https://unsplash.com/@frostyfilmsandphoto"
    }
  },
  "cottage-cheese-toast": {
    "url": "https://images.unsplash.com/photo-1606791479724-912d6f6b618b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwdG9hc3QlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1NHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1606791479724-912d6f6b618b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwdG9hc3QlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1NHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0c0d9",
    "alt": "blue round plate with sliced pizza",
    "attribution": {
      "name": "Christina Rumpf",
      "username": "rumpf",
      "photoLink": "https://unsplash.com/photos/blue-round-plate-with-sliced-pizza-enrolri1yi4",
      "userLink": "https://unsplash.com/@rumpf"
    }
  },
  "chia-pudding-jars": {
    "url": "https://images.unsplash.com/photo-1538187301321-a71d851901ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlhJTIwcHVkZGluZyUyMGphcnMlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1538187301321-a71d851901ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlhJTIwcHVkZGluZyUyMGphcnMlMjBicmVha2Zhc3R8ZW58MXwwfHx8MTc3Njg4MDQ1NXww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#262626",
    "alt": "clear glass mason jar on table",
    "attribution": {
      "name": "Artem Beliaikin",
      "username": "belart84",
      "photoLink": "https://unsplash.com/photos/clear-glass-mason-jar-on-table-_Sf6DDWGX64",
      "userLink": "https://unsplash.com/@belart84"
    }
  },
  "sheet-pan-pancakes": {
    "url": "https://images.unsplash.com/photo-1579629592346-3923f4110765?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMHBhbmNha2VzJTIwYnJlYWtmYXN0fGVufDF8MHx8fDE3NzY4ODA0NTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1579629592346-3923f4110765?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzaGVldCUyMHBhbiUyMHBhbmNha2VzJTIwYnJlYWtmYXN0fGVufDF8MHx8fDE3NzY4ODA0NTZ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#73738c",
    "alt": "sliced bread and sliced fruits on brown wooden tray",
    "attribution": {
      "name": "Phil Hearing",
      "username": "philhearing",
      "photoLink": "https://unsplash.com/photos/sliced-bread-and-sliced-fruits-on-brown-wooden-tray-jCe_8FO369c",
      "userLink": "https://unsplash.com/@philhearing"
    }
  },
  "leftover-dinner": {
    "url": "https://images.unsplash.com/photo-1623742999677-323531f1914e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxsZWZ0b3ZlciUyMGRpbm5lciUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDU3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1623742999677-323531f1914e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxsZWZ0b3ZlciUyMGRpbm5lciUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDU3fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0a68c",
    "alt": "cooked food in white ceramic bowl with chopsticks",
    "attribution": {
      "name": "Yeh Xintong",
      "username": "blsnki",
      "photoLink": "https://unsplash.com/photos/cooked-food-in-white-ceramic-bowl-with-chopsticks-z98hRE6sLDg",
      "userLink": "https://unsplash.com/@blsnki"
    }
  },
  "mediterranean-chicken-wrap": {
    "url": "https://images.unsplash.com/photo-1762631383556-7fa1365898b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtZWRpdGVycmFuZWFuJTIwY2hpY2tlbiUyMHdyYXAlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1762631383556-7fa1365898b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtZWRpdGVycmFuZWFuJTIwY2hpY2tlbiUyMHdyYXAlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1N3ww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#26260c",
    "alt": "Sliced grilled chicken with rice and beans",
    "attribution": {
      "name": "joe boshra",
      "username": "joestudios",
      "photoLink": "https://unsplash.com/photos/sliced-grilled-chicken-with-rice-and-beans-PSoXt5_8hNM",
      "userLink": "https://unsplash.com/@joestudios"
    }
  },
  "buffalo-chicken-wrap": {
    "url": "https://images.unsplash.com/photo-1603911036147-2f35cce108ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHdyYXAlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1OHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1603911036147-2f35cce108ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxidWZmYWxvJTIwY2hpY2tlbiUyMHdyYXAlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ1OHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#262626",
    "alt": "cooked food on white ceramic bowl",
    "attribution": {
      "name": "David Hunter",
      "username": "fla5h904",
      "photoLink": "https://unsplash.com/photos/cooked-food-on-white-ceramic-bowl-poVDDmE_4l0",
      "userLink": "https://unsplash.com/@fla5h904"
    }
  },
  "chicken-caesar-wrap": {
    "url": "https://images.unsplash.com/photo-1737588403883-41ad4be75bbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwY2Flc2FyJTIwd3JhcCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDU5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1737588403883-41ad4be75bbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwY2Flc2FyJTIwd3JhcCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDU5fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c8c8c",
    "alt": "A bowl of food on a wooden table",
    "attribution": {
      "name": "Didi Paul",
      "username": "didipaul",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-food-on-a-wooden-table-NLz9nr-TvQw",
      "userLink": "https://unsplash.com/@didipaul"
    }
  },
  "southwest-quinoa-power-bowl": {
    "url": "https://images.unsplash.com/photo-1543339162-b036159926ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzb3V0aHdlc3QlMjBxdWlub2ElMjBwb3dlciUyMGJvd2wlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ2MHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1543339162-b036159926ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzb3V0aHdlc3QlMjBxdWlub2ElMjBwb3dlciUyMGJvd2wlMjBsdW5jaCUyMGJvd2x8ZW58MXwwfHx8MTc3Njg4MDQ2MHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#595973",
    "alt": "plate of vegetable salad",
    "attribution": {
      "name": "Hermes Rivera",
      "username": "hermez777",
      "photoLink": "https://unsplash.com/photos/plate-of-vegetable-salad-l5ybbRJuV1Y",
      "userLink": "https://unsplash.com/@hermez777"
    }
  },
  "mason-jar-cobb-salad": {
    "url": "https://images.unsplash.com/photo-1722720774271-3ca416ffdb65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtYXNvbiUyMGphciUyMGNvYmIlMjBzYWxhZCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDYwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1722720774271-3ca416ffdb65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtYXNvbiUyMGphciUyMGNvYmIlMjBzYWxhZCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDYwfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9c0",
    "alt": "A bowl of salad next to a jar of dressing",
    "attribution": {
      "name": "Camille Bunim",
      "username": "camshands",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-salad-next-to-a-jar-of-dressing-tee5u0R-ylo",
      "userLink": "https://unsplash.com/@camshands"
    }
  },
  "turkey-and-hummus-wrap": {
    "url": "https://images.unsplash.com/photo-1752261355726-b723320edf2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBhbmQlMjBodW1tdXMlMjB3cmFwJTIwbHVuY2glMjBib3dsfGVufDF8MHx8fDE3NzY4ODA0NjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1752261355726-b723320edf2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBhbmQlMjBodW1tdXMlMjB3cmFwJTIwbHVuY2glMjBib3dsfGVufDF8MHx8fDE3NzY4ODA0NjF8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0c0c0",
    "alt": "A wrap, pickle, and sauce in a box.",
    "attribution": {
      "name": "Nathenia Landers",
      "username": "juicemetoo",
      "photoLink": "https://unsplash.com/photos/a-wrap-pickle-and-sauce-in-a-box-IMWiZ_QcPoA",
      "userLink": "https://unsplash.com/@juicemetoo"
    }
  },
  "cottage-cheese-bowl": {
    "url": "https://images.unsplash.com/photo-1644131448316-887558f9882b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwYm93bCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDYyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1644131448316-887558f9882b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwYm93bCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc2ODgwNDYyfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#a6a6a6",
    "alt": "a white bowl filled with vegetables and rice",
    "attribution": {
      "name": "Markus Winkler",
      "username": "markuswinkler",
      "photoLink": "https://unsplash.com/photos/a-white-bowl-filled-with-vegetables-and-rice-DA0U_xFQhxQ",
      "userLink": "https://unsplash.com/@markuswinkler"
    }
  },
  "hard-boiled-eggs": {
    "url": "https://images.unsplash.com/photo-1617611647086-bccca8c2cf84?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxoYXJkJTIwYm9pbGVkJTIwZWdncyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDQ2M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1617611647086-bccca8c2cf84?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxoYXJkJTIwYm9pbGVkJTIwZWdncyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDQ2M3ww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "white egg lot on brown wooden table",
    "attribution": {
      "name": "Mustafa Bashari",
      "username": "mustafabashari",
      "photoLink": "https://unsplash.com/photos/white-egg-lot-on-brown-wooden-table-rKUK4EB8F7s",
      "userLink": "https://unsplash.com/@mustafabashari"
    }
  },
  "apple-with-peanut-butter": {
    "url": "https://images.unsplash.com/photo-1642339800118-eb551cfa1434?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhcHBsZSUyMHdpdGglMjBwZWFudXQlMjBidXR0ZXIlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1642339800118-eb551cfa1434?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhcHBsZSUyMHdpdGglMjBwZWFudXQlMjBidXR0ZXIlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjR8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#262626",
    "alt": "a white plate topped with sliced apples and a bowl of peanut butter",
    "attribution": {
      "name": "Aasiya Khan",
      "username": "aasiyakhan",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-sliced-apples-and-a-bowl-of-peanut-butter-F-ReDCrjQbo",
      "userLink": "https://unsplash.com/@aasiyakhan"
    }
  },
  "greek-yogurt-granola": {
    "url": "https://images.unsplash.com/photo-1641494587136-eec74f1944ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMHlvZ3VydCUyMCUyQiUyMGdyYW5vbGElMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1641494587136-eec74f1944ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmVlayUyMHlvZ3VydCUyMCUyQiUyMGdyYW5vbGElMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjV8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a bowl of granola and yogurt with a spoon",
    "attribution": {
      "name": "Welcome",
      "username": "________________1a",
      "photoLink": "https://unsplash.com/photos/a-bowl-of-granola-and-yogurt-with-a-spoon-lE3LsH1Tx-I",
      "userLink": "https://unsplash.com/@________________1a"
    }
  },
  "cottage-cheese-fruit": {
    "url": "https://images.unsplash.com/photo-1613552496154-910202e418af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwJTJCJTIwZnJ1aXQlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1613552496154-910202e418af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjb3R0YWdlJTIwY2hlZXNlJTIwJTJCJTIwZnJ1aXQlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjV8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0d9d9",
    "alt": "red sauce on white ceramic bowl",
    "attribution": {
      "name": "Zizi zi",
      "username": "zizi_zi",
      "photoLink": "https://unsplash.com/photos/red-sauce-on-white-ceramic-bowl-k6MS6DupLZs",
      "userLink": "https://unsplash.com/@zizi_zi"
    }
  },
  "cheese-whole-grain-crackers": {
    "url": "https://images.unsplash.com/photo-1615294209152-571969a7fbfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGVlc2UlMjAlMkIlMjB3aG9sZSUyMGdyYWluJTIwY3JhY2tlcnMlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1615294209152-571969a7fbfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxjaGVlc2UlMjAlMkIlMjB3aG9sZSUyMGdyYWluJTIwY3JhY2tlcnMlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA0NjZ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9a659",
    "alt": "brown biscuits on white ceramic plate",
    "attribution": {
      "name": "Bohdan Stocek",
      "username": "bohdans",
      "photoLink": "https://unsplash.com/photos/brown-biscuits-on-white-ceramic-plate-ogoLAJboB6o",
      "userLink": "https://unsplash.com/@bohdans"
    }
  },
  "edamame": {
    "url": "https://images.unsplash.com/photo-1730595807253-c7f5168a47da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxlZGFtYW1lJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1730595807253-c7f5168a47da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxlZGFtYW1lJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY2fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c4026",
    "alt": "A wooden table topped with plates and bowls of food",
    "attribution": {
      "name": "Kat",
      "username": "northernpaws",
      "photoLink": "https://unsplash.com/photos/a-wooden-table-topped-with-plates-and-bowls-of-food-8hnpNtt-LoQ",
      "userLink": "https://unsplash.com/@northernpaws"
    }
  },
  "roasted-chickpeas": {
    "url": "https://images.unsplash.com/photo-1776057302065-45780d0b7631?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxyb2FzdGVkJTIwY2hpY2twZWFzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1776057302065-45780d0b7631?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxyb2FzdGVkJTIwY2hpY2twZWFzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY3fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9a659",
    "alt": "Close-up of a pile of roasted chickpeas",
    "attribution": {
      "name": "Mustafa akın",
      "username": "msaimakin",
      "photoLink": "https://unsplash.com/photos/close-up-of-a-pile-of-roasted-chickpeas-Fr4lk6RdnFg",
      "userLink": "https://unsplash.com/@msaimakin"
    }
  },
  "turkey-and-cheese-rollups": {
    "url": "https://images.unsplash.com/photo-1676300187437-f09c6397a959?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBhbmQlMjBjaGVlc2UlMjByb2xsdXBzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1676300187437-f09c6397a959?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBhbmQlMjBjaGVlc2UlMjByb2xsdXBzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY4fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a white plate topped with a cut in half sandwich",
    "attribution": {
      "name": "Orkun Orcan",
      "username": "orkunorcan",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-a-cut-in-half-sandwich-r6pmTZiNrJc",
      "userLink": "https://unsplash.com/@orkunorcan"
    }
  },
  "almonds-dried-apricots": {
    "url": "https://images.unsplash.com/photo-1768284952322-58905fef0f16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhbG1vbmRzJTIwJTJCJTIwZHJpZWQlMjBhcHJpY290cyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDQ2OHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1768284952322-58905fef0f16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhbG1vbmRzJTIwJTJCJTIwZHJpZWQlMjBhcHJpY290cyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDQ2OHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#262626",
    "alt": "Outdoor stall selling various dried fruits and nuts",
    "attribution": {
      "name": "Wenzy Wong",
      "username": "wenzywong",
      "photoLink": "https://unsplash.com/photos/outdoor-stall-selling-various-dried-fruits-and-nuts-9DmvTzBFAos",
      "userLink": "https://unsplash.com/@wenzywong"
    }
  },
  "smoothie-with-protein-powder": {
    "url": "https://images.unsplash.com/photo-1621878974676-a41806cc9ed1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzbW9vdGhpZSUyMHdpdGglMjBwcm90ZWluJTIwcG93ZGVyJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1621878974676-a41806cc9ed1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxzbW9vdGhpZSUyMHdpdGglMjBwcm90ZWluJTIwcG93ZGVyJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDY5fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9c0c0",
    "alt": "white and green labeled plastic bottle",
    "attribution": {
      "name": "Nature Zen",
      "username": "nature_zen",
      "photoLink": "https://unsplash.com/photos/white-and-green-labeled-plastic-bottle-awBT427pSKE",
      "userLink": "https://unsplash.com/@nature_zen"
    }
  },
  "oatmeal-with-pb-and-banana": {
    "url": "https://images.unsplash.com/photo-1573688886153-76daa1aff29c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxvYXRtZWFsJTIwd2l0aCUyMHBiJTIwYW5kJTIwYmFuYW5hJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDcwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1573688886153-76daa1aff29c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxvYXRtZWFsJTIwd2l0aCUyMHBiJTIwYW5kJTIwYmFuYW5hJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDcwfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#262626",
    "alt": "selective focus photography of sliced fruits on bowl",
    "attribution": {
      "name": "Jakub Durian",
      "username": "jakubdurian",
      "photoLink": "https://unsplash.com/photos/selective-focus-photography-of-sliced-fruits-on-bowl-pvFciANDmrI",
      "userLink": "https://unsplash.com/@jakubdurian"
    }
  },
  "hummus-carrots-and-pepper-strips": {
    "url": "https://images.unsplash.com/photo-1683725519288-eab9fa352335?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxodW1tdXMlMjAlMkIlMjBjYXJyb3RzJTIwYW5kJTIwcGVwcGVyJTIwc3RyaXBzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDcxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1683725519288-eab9fa352335?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxodW1tdXMlMjAlMkIlMjBjYXJyb3RzJTIwYW5kJTIwcGVwcGVyJTIwc3RyaXBzJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwNDcxfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#a6a6a6",
    "alt": "a plate of hummus, carrots, and pita bread",
    "attribution": {
      "name": "Riddhi K",
      "username": "riddhik11",
      "photoLink": "https://unsplash.com/photos/a-plate-of-hummus-carrots-and-pita-bread-enRLKyJLxrk",
      "userLink": "https://unsplash.com/@riddhik11"
    }
  },
  "tuna-packet-crackers": {
    "url": "https://images.unsplash.com/photo-1598726466121-c1e15a875850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dW5hJTIwcGFja2V0JTIwJTJCJTIwY3JhY2tlcnMlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA4MzN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1598726466121-c1e15a875850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dW5hJTIwcGFja2V0JTIwJTJCJTIwY3JhY2tlcnMlMjBmb29kfGVufDF8MHx8fDE3NzY4ODA4MzN8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#260c0c",
    "alt": "brown french fries on blue ceramic plate",
    "attribution": {
      "name": "Clyde Gravenberch",
      "username": "mediainspire",
      "photoLink": "https://unsplash.com/photos/brown-french-fries-on-blue-ceramic-plate-Yt5Llh3BlbU",
      "userLink": "https://unsplash.com/@mediainspire"
    }
  },
  "deviled-eggs": {
    "url": "https://images.unsplash.com/photo-1626895597772-74988e263fab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxkZXZpbGVkJTIwZWdncyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDgzNHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1626895597772-74988e263fab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxkZXZpbGVkJTIwZWdncyUyMGZvb2R8ZW58MXwwfHx8MTc3Njg4MDgzNHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#737373",
    "alt": "white and yellow icing covered cupcakes",
    "attribution": {
      "name": "Rosalie Barley",
      "username": "rosiebarley",
      "photoLink": "https://unsplash.com/photos/white-and-yellow-icing-covered-cupcakes-qb8EK1uQF9w",
      "userLink": "https://unsplash.com/@rosiebarley"
    }
  },
  "avocado-toast-with-egg": {
    "url": "https://images.unsplash.com/photo-1540149483947-068ef716f86f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhdm9jYWRvJTIwdG9hc3QlMjB3aXRoJTIwZWdnJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwODM1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1540149483947-068ef716f86f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhdm9jYWRvJTIwdG9hc3QlMjB3aXRoJTIwZWdnJTIwZm9vZHxlbnwxfDB8fHwxNzc2ODgwODM1fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#264040",
    "alt": "toasted bread with dip",
    "attribution": {
      "name": "Lior Shapira",
      "username": "shapira",
      "photoLink": "https://unsplash.com/photos/toasted-bread-with-dip-ZJ0CzsNo48M",
      "userLink": "https://unsplash.com/@shapira"
    }
  },
  "mississippi-pot-roast": {
    "url": "https://images.unsplash.com/photo-1622003275933-fc87f54913ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwb3QlMjByb2FzdCUyMGJlZWZ8ZW58MXwwfHx8MTc3Njg4MzgxMHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1622003275933-fc87f54913ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwb3QlMjByb2FzdCUyMGJlZWZ8ZW58MXwwfHx8MTc3Njg4MzgxMHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "sliced meat on white ceramic plate",
    "attribution": {
      "name": "ThermoPro",
      "username": "thermopro",
      "photoLink": "https://unsplash.com/photos/sliced-meat-on-white-ceramic-plate-wAkmA9I54dY",
      "userLink": "https://unsplash.com/@thermopro"
    }
  },
  "power-protein-smoothie": {
    "url": "https://images.unsplash.com/photo-1662130187270-a4d52c700eb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwc21vb3RoaWUlMjBnbGFzc3xlbnwxfDB8fHwxNzc2ODgzODEwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1662130187270-a4d52c700eb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxwcm90ZWluJTIwc21vb3RoaWUlMjBnbGFzc3xlbnwxfDB8fHwxNzc2ODgzODEwfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f3f3f3",
    "alt": "a group of different colored drinks",
    "attribution": {
      "name": "Fanny Gustafsson",
      "username": "fannygustafsson",
      "photoLink": "https://unsplash.com/photos/a-group-of-different-colored-drinks-71z7eCLS4Uo",
      "userLink": "https://unsplash.com/@fannygustafsson"
    }
  },
  "tuna-salad-on-whole-grain": {
    "url": "https://images.unsplash.com/photo-1558985250-27a406d64cb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dW5hJTIwc2FsYWQlMjBzYW5kd2ljaHxlbnwxfDB8fHwxNzc2ODgzODExfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1558985250-27a406d64cb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dW5hJTIwc2FsYWQlMjBzYW5kd2ljaHxlbnwxfDB8fHwxNzc2ODgzODExfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#a6c0c0",
    "alt": "sandwich on table",
    "attribution": {
      "name": "Youjeen Cho",
      "username": "youjeencho",
      "photoLink": "https://unsplash.com/photos/sandwich-on-table-sBKLiRiunK0",
      "userLink": "https://unsplash.com/@youjeencho"
    }
  },
  "asian-turkey-lettuce-wraps": {
    "url": "https://images.unsplash.com/photo-1593967858534-40654ea9607b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHR1cmtleSUyMGxldHR1Y2UlMjB3cmFwcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTcwMzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1593967858534-40654ea9607b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHR1cmtleSUyMGxldHR1Y2UlMjB3cmFwcyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTcwMzF8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "sliced cucumber and meat on white and blue ceramic plate",
    "attribution": {
      "name": "K8",
      "username": "_k8_",
      "photoLink": "https://unsplash.com/photos/sliced-cucumber-and-meat-on-white-and-blue-ceramic-plate-ghLUN41rtEM",
      "userLink": "https://unsplash.com/@_k8_"
    }
  },
  "turkey-burgers-with-avocado-and-slaw": {
    "url": "https://images.unsplash.com/photo-1693845261682-4ae639e88e6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBidXJnZXJzJTIwd2l0aCUyMGF2b2NhZG8lMjBhbmQlMjBzbGF3JTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxNzAzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1693845261682-4ae639e88e6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0dXJrZXklMjBidXJnZXJzJTIwd2l0aCUyMGF2b2NhZG8lMjBhbmQlMjBzbGF3JTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxNzAzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#8c8c73",
    "alt": "a plate with a hamburger and chips on it",
    "attribution": {
      "name": "Natilyn Hicks Photography",
      "username": "natilyn",
      "photoLink": "https://unsplash.com/photos/a-plate-with-a-hamburger-and-chips-on-it-Igp-rAKTB0I",
      "userLink": "https://unsplash.com/@natilyn"
    }
  },
  "asian-sesame-chicken-salad": {
    "url": "https://images.unsplash.com/photo-1676300186659-030de568e39a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHNlc2FtZSUyMGNoaWNrZW4lMjBzYWxhZCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc5MzE3MDMzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1676300186659-030de568e39a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHNlc2FtZSUyMGNoaWNrZW4lMjBzYWxhZCUyMGx1bmNoJTIwYm93bHxlbnwxfDB8fHwxNzc5MzE3MDMzfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a white bowl filled with lettuce and chicken",
    "attribution": {
      "name": "Orkun Orcan",
      "username": "orkunorcan",
      "photoLink": "https://unsplash.com/photos/a-white-bowl-filled-with-lettuce-and-chicken-x-YS_Z_YPns",
      "userLink": "https://unsplash.com/@orkunorcan"
    }
  },
  "korean-beef-bowls": {
    "url": "https://images.unsplash.com/photo-1673960616288-0cb46f318a68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxrb3JlYW4lMjBiZWVmJTIwYm93bHMlMjBkaW5uZXIlMjBwbGF0ZXxlbnwxfDB8fHwxNzc5MzE3MDM0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1673960616288-0cb46f318a68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxrb3JlYW4lMjBiZWVmJTIwYm93bHMlMjBkaW5uZXIlMjBwbGF0ZXxlbnwxfDB8fHwxNzc5MzE3MDM0fDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a white plate topped with meat and rice",
    "attribution": {
      "name": "Sandie Clarke",
      "username": "honeypoppet",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-meat-and-rice-I5RmU0wtvpw",
      "userLink": "https://unsplash.com/@honeypoppet"
    }
  },
  "grilled-shrimp-tacos-with-mango-salsa": {
    "url": "https://images.unsplash.com/photo-1611699363917-71e903ed1a25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwc2hyaW1wJTIwdGFjb3MlMjB3aXRoJTIwbWFuZ28lMjBzYWxzYSUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTcwMzR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1611699363917-71e903ed1a25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwc2hyaW1wJTIwdGFjb3MlMjB3aXRoJTIwbWFuZ28lMjBzYWxzYSUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTcwMzR8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#f38cc0",
    "alt": "brown and white dish on white ceramic plate",
    "attribution": {
      "name": "Davey Gravy",
      "username": "davey_gravy",
      "photoLink": "https://unsplash.com/photos/brown-and-white-dish-on-white-ceramic-plate-vQz3vuFMEl4",
      "userLink": "https://unsplash.com/@davey_gravy"
    }
  },
  "sheet-pan-honey-soy-salmon": {
    "url": "https://images.unsplash.com/photo-1627857638952-642f8cbba8da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxnbGF6ZWQlMjBzYWxtb24lMjBicm9jY29saXxlbnwxfDB8fHwxNzc5MzE3MDYzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1627857638952-642f8cbba8da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxnbGF6ZWQlMjBzYWxtb24lMjBicm9jY29saXxlbnwxfDB8fHwxNzc5MzE3MDYzfDA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#26260c",
    "alt": "brown bread on white ceramic plate",
    "attribution": {
      "name": "Ben Libby",
      "username": "blibbs86",
      "photoLink": "https://unsplash.com/photos/brown-bread-on-white-ceramic-plate-xJBeGxiSYBE",
      "userLink": "https://unsplash.com/@blibbs86"
    }
  },
  "miso-glazed-salmon": {
    "url": "https://images.unsplash.com/photo-1580214083041-72c0d930f13e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtaXNvJTIwZ2xhemVkJTIwc2FsbW9uJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxODE0NHww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1580214083041-72c0d930f13e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxtaXNvJTIwZ2xhemVkJTIwc2FsbW9uJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxODE0NHww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0c0c0",
    "alt": "cooked food on white ceramic plate",
    "attribution": {
      "name": "CHUTTERSNAP",
      "username": "chuttersnap",
      "photoLink": "https://unsplash.com/photos/cooked-food-on-white-ceramic-plate-cVjvdAZvCt4",
      "userLink": "https://unsplash.com/@chuttersnap"
    }
  },
  "thai-basil-chicken": {
    "url": "https://images.unsplash.com/photo-1652265540600-a319e0e4fd81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0aGFpJTIwYmFzaWwlMjBjaGlja2VuJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxODE0NXww&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1652265540600-a319e0e4fd81?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHx0aGFpJTIwYmFzaWwlMjBjaGlja2VuJTIwZGlubmVyJTIwcGxhdGV8ZW58MXwwfHx8MTc3OTMxODE0NXww&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a plate of food",
    "attribution": {
      "name": "Markus Winkler",
      "username": "markuswinkler",
      "photoLink": "https://unsplash.com/photos/a-plate-of-food-7XESYTzyUWw",
      "userLink": "https://unsplash.com/@markuswinkler"
    }
  },
  "beef-burgers-with-caramelized-onions": {
    "url": "https://images.unsplash.com/photo-1673646961402-df39d8c32448?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYnVyZ2VycyUyMHdpdGglMjBjYXJhbWVsaXplZCUyMG9uaW9ucyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTgxNDV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1673646961402-df39d8c32448?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYnVyZ2VycyUyMHdpdGglMjBjYXJhbWVsaXplZCUyMG9uaW9ucyUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTgxNDV8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#c0c0c0",
    "alt": "a white plate topped with meat and vegetables",
    "attribution": {
      "name": "Natalia Gusakova",
      "username": "nataliaraylenegusakova",
      "photoLink": "https://unsplash.com/photos/a-white-plate-topped-with-meat-and-vegetables-NTPrgH82SBA",
      "userLink": "https://unsplash.com/@nataliaraylenegusakova"
    }
  },
  "beef-stroganoff": {
    "url": "https://images.unsplash.com/photo-1693296303873-126aa7f6e5b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwc3Ryb2dhbm9mZiUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTkzOTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "smallUrl": "https://images.unsplash.com/photo-1693296303873-126aa7f6e5b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzI0ODB8MHwxfHNlYXJjaHwxfHxiZWVmJTIwc3Ryb2dhbm9mZiUyMGRpbm5lciUyMHBsYXRlfGVufDF8MHx8fDE3NzkzMTkzOTN8MA&ixlib=rb-4.1.0&q=80&w=400",
    "blurColor": "#d9d9d9",
    "alt": "a black plate topped with mushrooms and rice",
    "attribution": {
      "name": "The Design Lady",
      "username": "sarah35",
      "photoLink": "https://unsplash.com/photos/a-black-plate-topped-with-mushrooms-and-rice-LEBpfkaYb3I",
      "userLink": "https://unsplash.com/@sarah35"
    }
  }
};
