// GENERATED by scripts/extract.py. Do not edit by hand.
import type { Nutrition } from "./types";

export const nutrition: Nutrition = {
  "intro": "Not medical advice. Confirm anything specific with Emily's OB or midwife.",
  "sections": [
    {
      "title": "Daily targets (rough)",
      "items": [
        {
          "label": "Protein",
          "value": "75 to 100 g/day. This plan averages 30 g per dinner, 22 g per breakfast, 15 g per snack = ~100 g easily hit with 2 snacks."
        },
        {
          "label": "Calories",
          "value": "Extra 340 kcal/day above baseline in second trimester. This is roughly an extra snack or a generous glass of whole milk plus nut butter toast."
        },
        {
          "label": "Iron",
          "value": "27 mg/day. Double non pregnant. Red meat, lentils, spinach, fortified grains, dried apricots. Pair with vitamin C (peppers, citrus) for absorption."
        },
        {
          "label": "Folate",
          "value": "600 mcg/day. Leafy greens, lentils, asparagus, fortified grains, oranges, avocado."
        },
        {
          "label": "Calcium",
          "value": "1000 mg/day. Dairy, fortified plant milks, broccoli, kale, canned salmon with bones."
        },
        {
          "label": "DHA / Omega 3",
          "value": "200 to 300 mg DHA/day. Salmon twice a week in this plan hits this. Chia and walnuts are supplemental."
        },
        {
          "label": "Fiber",
          "value": "28 g/day. Whole grains, beans, veg, fruit. Helps with pregnancy constipation."
        },
        {
          "label": "Hydration",
          "value": "About 10 cups/day. Extra during exercise or warm weather."
        },
        {
          "label": "Caffeine",
          "value": "Under 200 mg/day (one 12 oz coffee). Your call on how strict to be."
        }
      ]
    },
    {
      "title": "Foods being avoided in this plan",
      "items": [
        {
          "label": "High mercury fish",
          "value": "Shark, swordfish, king mackerel, tilefish, bigeye tuna, marlin, orange roughy. Salmon, cod, tilapia, shrimp, light canned tuna in limited amounts are all in."
        },
        {
          "label": "Raw/undercooked meat and fish",
          "value": "No sushi with raw fish, carpaccio, tartare, rare burgers. All meat cooked to safe internal temps (chicken 165F, beef steaks 145F rest, ground 160F, pork 145F, fish 145F)."
        },
        {
          "label": "Raw or runny eggs",
          "value": "All eggs in this plan cooked through. Homemade caesar dressing and raw cookie dough are out."
        },
        {
          "label": "Deli meats unheated",
          "value": "Listeria risk. Turkey wraps in this plan specify heating to steaming. Safer option: substitute rotisserie chicken or shredded chicken."
        },
        {
          "label": "Unpasteurized dairy and soft cheeses",
          "value": "No unpasteurized milk, feta, brie, camembert, blue cheese, queso fresco unless labeled pasteurized. All cheeses in this plan specify pasteurized."
        },
        {
          "label": "Unpasteurized juice and cider",
          "value": "Stick to pasteurized."
        },
        {
          "label": "Raw sprouts",
          "value": "Alfalfa, clover, radish, mung. Not in this plan."
        },
        {
          "label": "Alcohol",
          "value": "Out."
        },
        {
          "label": "Excess liver",
          "value": "High vitamin A. Limit pate and liver dishes."
        }
      ]
    },
    {
      "title": "High iron meals in this plan",
      "items": [
        {
          "label": "Mississippi Pot Roast and Beef Barbacoa Tacos",
          "value": "Beef is a top bioavailable iron source."
        },
        {
          "label": "Beef and Barley Soup",
          "value": "Beef plus barley plus kale."
        },
        {
          "label": "Red Lentil Soup",
          "value": "Plant iron, pair with lemon (vitamin C) which the recipe already does."
        },
        {
          "label": "Stuffed Peppers with Turkey and Quinoa",
          "value": "Quinoa is an underrated iron source, plus peppers for vitamin C."
        },
        {
          "label": "Spinach appearances",
          "value": "In egg muffins, dump soup, wedding soup, smoothies, wraps."
        }
      ]
    },
    {
      "title": "If Emily loses appetite or feels nauseous",
      "items": [
        {
          "label": "Switch to small frequent meals",
          "value": "The snack list has 15 options ranging 8 to 25 g protein. 5 to 6 small meals beats 3 big ones on rough days."
        },
        {
          "label": "Prioritize bland carbs with protein",
          "value": "Cottage cheese toast, scrambled eggs on sourdough, plain pasta with meatballs, rice with shredded chicken. All in this plan."
        },
        {
          "label": "Lean on the freezer backup",
          "value": "That's literally what it's there for."
        },
        {
          "label": "Ginger and lemon",
          "value": "Ginger chews, lemon water. Nothing in this plan blocks adding these."
        }
      ]
    }
  ]
};
