// GENERATED by scripts/extract.py. Do not edit by hand.
import type { PrepWeek } from "./types";

export const prep: PrepWeek[] = [
  {
    "week": 1,
    "dateLabel": "Sun Apr 26 or Sat eve",
    "steps": [
      {
        "label": "Step 1",
        "action": "Start Instant Pot: shredded chicken thighs with onion, garlic, spices, broth, lime. 15 min pressure + 10 min natural release.",
        "approx": "30 min"
      },
      {
        "label": "Step 2",
        "action": "While Instant Pot runs: bake egg muffins in oven (22 min at 375F).",
        "approx": "25 min"
      },
      {
        "label": "Step 3",
        "action": "Assemble 4 jars overnight oats (PB + banana + berries). Shake, fridge.",
        "approx": "10 min"
      },
      {
        "label": "Step 4",
        "action": "Cut snack veg: carrots, cucumber, peppers into containers. Wash berries.",
        "approx": "15 min"
      },
      {
        "label": "Step 5",
        "action": "Shred chicken in Instant Pot when done. Portion: 2.5 cups for Sat enchilada skillet (fridge), rest for Fri tacos.",
        "approx": "5 min"
      }
    ]
  },
  {
    "week": 2,
    "dateLabel": "Sun May 3",
    "steps": [
      {
        "label": "Step 1",
        "action": "Stuffed peppers: par boil peppers, brown turkey, mix filling, assemble 5 peppers in baking dish. Bake tonight for dinner. Freeze 1 filled raw pepper as backup.",
        "approx": "60 min total including dinner"
      },
      {
        "label": "Step 2",
        "action": "Sunday Instant Pot: nothing this week (spreads into Wed with pot roast).",
        "approx": null
      },
      {
        "label": "Step 3",
        "action": "Cook 3 cups quinoa (doubles for stuffed peppers + power bowls). Also cook 2 cups rice for leftovers and bowls.",
        "approx": "25 min"
      },
      {
        "label": "Step 4",
        "action": "Breakfast prep: make 6 breakfast burritos and freeze individually wrapped. Make egg muffins if you want variety (optional).",
        "approx": "40 min"
      },
      {
        "label": "Step 5",
        "action": "Overnight oats x4. Wash spinach. Prep snack boxes.",
        "approx": "15 min"
      }
    ]
  },
  {
    "week": 3,
    "dateLabel": "Sun May 10",
    "steps": [
      {
        "label": "Step 1",
        "action": "Instant Pot pulled pork: rub pork, sauté to brown, pressure cook 65 min + 15 min natural release. Serve tonight as BBQ sandwiches. Save 2.5 cups plain pork for Mon carnitas. Freeze 2 cups as Week 3 backup.",
        "approx": "90 min"
      },
      {
        "label": "Step 2",
        "action": "Make slaw dressing and toss with cabbage 30 min before dinner.",
        "approx": "10 min"
      },
      {
        "label": "Step 3",
        "action": "While pork runs: breakfast prep. Chia pudding x4 jars. Egg muffins batch. Or overnight oats.",
        "approx": "40 min"
      },
      {
        "label": "Step 4",
        "action": "Cook 3 cups rice (carnitas bowls, lunch bowls). Prep mason jar cobb salads for Sat.",
        "approx": "30 min"
      },
      {
        "label": "Step 5",
        "action": "Cut snack veg, wash fruit, portion almonds.",
        "approx": "15 min"
      }
    ]
  },
  {
    "week": 4,
    "dateLabel": "Sun May 17",
    "steps": [
      {
        "label": "Step 1",
        "action": "Instant Pot shredded chicken round 2: same method as Week 1. Pressure 15 min + 10 min NR. Save 2.5 cups for Mon stuffed sweet potatoes, 2.5 cups for Tue enchilada skillet. Use rest tonight for tacos.",
        "approx": "40 min"
      },
      {
        "label": "Step 2",
        "action": "Breakfast prep: protein smoothie pack bags (freeze banana, berries, spinach, PB in individual bags, grab and blend each morning).",
        "approx": "15 min"
      },
      {
        "label": "Step 3",
        "action": "Make 20 turkey meatballs raw. Put 10 on a sheet pan to freeze individually, then bag (for Wed dinner). Other 10 ready for Wed.",
        "approx": "20 min"
      },
      {
        "label": "Step 4",
        "action": "Cook 2 cups quinoa, 2 cups rice. Prep power bowl components (chickpeas drained, corn, diced peppers).",
        "approx": "25 min"
      },
      {
        "label": "Step 5",
        "action": "Wash greens. Prep wrap fillings (shredded chicken in buffalo sauce jar, tzatziki jar, etc.).",
        "approx": "20 min"
      }
    ]
  },
  {
    "week": 5,
    "dateLabel": "Sun May 24",
    "steps": [
      {
        "label": "Step 1",
        "action": "Instant Pot pulled pork round 2. Same as Week 3. Serve tonight BBQ. Save 2.5 cups plain for Mon carnitas.",
        "approx": "90 min"
      },
      {
        "label": "Step 2",
        "action": "Breakfast prep: assemble 6 more breakfast burritos (useful for Memorial Day weekend).",
        "approx": "40 min"
      },
      {
        "label": "Step 3",
        "action": "Cook rice, wash kale for white bean soup Tuesday. Make slaw.",
        "approx": "20 min"
      },
      {
        "label": "Step 4",
        "action": "Snack restock, fruit wash, hard boil 6 eggs.",
        "approx": "15 min"
      },
      {
        "label": "Step 5",
        "action": "Optional: make a double batch chicken tortilla soup ingredient mise en place for Saturday so it's a true dump and go.",
        "approx": "10 min"
      }
    ]
  }
];
