// GENERATED by scripts/extract.py. Do not edit by hand.
import type { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    "slug": "shredded-chicken-street-tacos",
    "name": "Shredded Chicken Street Tacos",
    "category": "dinner",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 38,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 30,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Instant Pot Meat Base",
      "High Protein",
      "Mexican",
      "Dinner"
    ],
    "ingredients": [
      "3 lb boneless skinless chicken thighs",
      "1 tbsp olive oil",
      "1 yellow onion, diced",
      "4 garlic cloves, minced",
      "1.5 tbsp chili powder",
      "1 tbsp cumin",
      "1 tsp smoked paprika",
      "1 tsp salt",
      "1 cup low sodium chicken broth",
      "Juice of 1 lime",
      "Small corn tortillas",
      "Toppings: diced white onion, cilantro, avocado, pico de gallo, lime",
      "Queso fresco (pasteurized)"
    ],
    "steps": [
      "Set Instant Pot to Sauté. Heat oil, cook onion 3 min, add garlic, spices, cook 1 min.",
      "Add chicken thighs, broth, and lime juice. Lock lid.",
      "Pressure cook High 15 min, natural release 10 min.",
      "Shred chicken in the pot with two forks, stir to coat in liquid.",
      "Char tortillas over gas burner or in dry skillet.",
      "Build tacos with chicken, onion, cilantro, avocado, queso fresco."
    ],
    "notes": null
  },
  {
    "slug": "buffalo-chicken-stuffed-sweet-potatoes",
    "name": "Buffalo Chicken Stuffed Sweet Potatoes",
    "category": "dinner",
    "tool": "Oven + reuses Instant Pot chicken",
    "proteinGrams": 42,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 50,
    "tags": [
      "Oven",
      "Reuses Instant Pot Meat",
      "High Protein",
      "Dinner"
    ],
    "ingredients": [
      "4 medium sweet potatoes",
      "2.5 cups reserved shredded chicken",
      "1/3 cup Frank's RedHot",
      "3 tbsp butter, melted",
      "1/2 cup plain Greek yogurt",
      "2 tbsp ranch seasoning",
      "1/2 cup crumbled blue cheese (pasteurized) or feta",
      "2 green onions, sliced"
    ],
    "steps": [
      "Oven 425F. Pierce sweet potatoes, roast on sheet pan 45-50 min until soft.",
      "Toss shredded chicken with hot sauce and melted butter, warm in skillet.",
      "Whisk yogurt with ranch seasoning for drizzle.",
      "Split open potatoes, pile in buffalo chicken, drizzle ranch, top with cheese and green onion."
    ],
    "notes": null
  },
  {
    "slug": "chicken-enchilada-skillet",
    "name": "Chicken Enchilada Skillet",
    "category": "dinner",
    "tool": "Sauté + Oven + reuses Instant Pot chicken",
    "proteinGrams": 41,
    "servings": 4,
    "prepMin": 15,
    "cookMin": 25,
    "tags": [
      "Sauté",
      "Oven",
      "Reuses Instant Pot Meat",
      "High Protein",
      "Mexican",
      "Dinner"
    ],
    "ingredients": [
      "2.5 cups reserved shredded chicken",
      "1 tbsp olive oil",
      "1 yellow onion, diced",
      "1 red bell pepper, diced",
      "1 (15 oz) can black beans, drained",
      "1 cup frozen corn",
      "2 cups red enchilada sauce",
      "8 corn tortillas, torn into pieces",
      "2 cups shredded Monterey Jack (pasteurized)",
      "Cilantro, green onion, avocado to top"
    ],
    "steps": [
      "Oven 400F. In oven-safe skillet, sauté onion and pepper 5 min.",
      "Stir in chicken, beans, corn, enchilada sauce, and torn tortillas.",
      "Top with cheese, bake 15 min until bubbly.",
      "Garnish with cilantro, green onion, avocado."
    ],
    "notes": null
  },
  {
    "slug": "mississippi-pot-roast",
    "name": "Mississippi Pot Roast",
    "category": "dinner",
    "tool": "Instant Pot",
    "proteinGrams": 45,
    "servings": 6,
    "prepMin": 5,
    "cookMin": 80,
    "tags": [
      "Instant Pot",
      "Instant Pot Meat Base",
      "High Protein",
      "Iron Rich",
      "Dinner"
    ],
    "ingredients": [
      "3.5 lb chuck roast",
      "1 packet ranch seasoning",
      "1 packet au jus gravy mix",
      "1 stick unsalted butter",
      "8 pepperoncini peppers + 1/4 cup brine",
      "1 cup beef broth",
      "4 cups mashed potatoes (for serving)",
      "Steamed green beans"
    ],
    "steps": [
      "Season roast with salt and pepper. Set Instant Pot to Sauté, brown roast all sides 2 min each.",
      "Add broth, ranch and au jus packets, butter, pepperoncini and brine.",
      "Pressure cook High 70 min, natural release 15 min.",
      "Shred beef in the pot, serve 1/3 over mashed potatoes with green beans.",
      "Reserve remaining beef for Beef Barbacoa Tacos."
    ],
    "notes": null
  },
  {
    "slug": "beef-barbacoa-tacos",
    "name": "Beef Barbacoa Tacos",
    "category": "dinner",
    "tool": "Sauté + reuses Instant Pot beef",
    "proteinGrams": 40,
    "servings": 4,
    "prepMin": 5,
    "cookMin": 15,
    "tags": [
      "Sauté",
      "Reuses Instant Pot Meat",
      "High Protein",
      "Quick",
      "Mexican",
      "Iron Rich",
      "Dinner"
    ],
    "ingredients": [
      "2.5 cups reserved shredded beef + cooking liquid",
      "1 tsp cumin",
      "1 tsp smoked paprika",
      "1 chipotle in adobo, minced (optional)",
      "Juice of 1 lime",
      "Small flour or corn tortillas",
      "Diced white onion, cilantro, cotija or queso fresco",
      "Mexican rice, black beans"
    ],
    "steps": [
      "Warm shredded beef in skillet with cumin, paprika, chipotle, and lime juice.",
      "Let sauce reduce until beef is glossy, 8-10 min.",
      "Char tortillas, build tacos with onion, cilantro, cotija.",
      "Serve with rice and beans."
    ],
    "notes": null
  },
  {
    "slug": "bbq-pulled-pork-sandwiches-with-slaw",
    "name": "BBQ Pulled Pork Sandwiches with Slaw",
    "category": "dinner",
    "tool": "Instant Pot",
    "proteinGrams": 44,
    "servings": 6,
    "prepMin": 10,
    "cookMin": 75,
    "tags": [
      "Instant Pot",
      "Instant Pot Meat Base",
      "Freezer Backup",
      "High Protein",
      "BBQ",
      "Dinner"
    ],
    "ingredients": [
      "3.5 lb boneless pork shoulder, cut into 3 chunks",
      "1 tbsp smoked paprika",
      "1 tbsp brown sugar",
      "2 tsp salt",
      "1 tsp garlic powder, 1 tsp onion powder",
      "1 cup chicken broth",
      "2 tbsp apple cider vinegar",
      "1.5 cups BBQ sauce, divided",
      "Brioche buns",
      "1 bag coleslaw mix + 1/2 cup mayo, 2 tbsp vinegar, 1 tbsp sugar, salt"
    ],
    "steps": [
      "Rub pork with paprika, brown sugar, salt, garlic, onion powder.",
      "Sauté in Instant Pot to brown 2 min per side. Add broth and vinegar. Lock lid.",
      "Pressure cook High 65 min, natural release 15 min.",
      "Shred pork, toss half with BBQ sauce for sandwiches tonight, save rest plain for Carnitas Bowls.",
      "Whisk slaw dressing, toss with cabbage mix 10 min before serving.",
      "Pile pork on buns, top with slaw. Freeze one portion of shredded pork in 2-cup container."
    ],
    "notes": null
  },
  {
    "slug": "carnitas-bowls",
    "name": "Carnitas Bowls",
    "category": "dinner",
    "tool": "Air Fryer + reuses pulled pork",
    "proteinGrams": 43,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 15,
    "tags": [
      "Air Fryer",
      "Reuses Instant Pot Meat",
      "High Protein",
      "Quick",
      "Mexican",
      "Dinner"
    ],
    "ingredients": [
      "2.5 cups reserved plain pulled pork",
      "2 tbsp orange juice",
      "1 tsp cumin, 1 tsp oregano",
      "2 cups cooked cilantro lime rice",
      "1 can black beans, warmed",
      "Toppings: avocado, pico de gallo, lime, cilantro, queso fresco",
      "1 head romaine or cabbage, shredded"
    ],
    "steps": [
      "Toss pork with OJ, cumin, oregano. Spread on air fryer tray.",
      "Air fry 400F for 8-10 min until crispy edges.",
      "Build bowls with rice, beans, crispy carnitas, slaw, toppings."
    ],
    "notes": null
  },
  {
    "slug": "sheet-pan-salmon-with-lemon-asparagus-and-potatoes",
    "name": "Sheet Pan Salmon with Lemon Asparagus and Potatoes",
    "category": "dinner",
    "tool": "Sheet Pan",
    "proteinGrams": 36,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 25,
    "tags": [
      "Sheet Pan",
      "Omega-3",
      "High Protein",
      "Dinner"
    ],
    "ingredients": [
      "4 (6 oz) salmon fillets, skin on",
      "1.5 lb baby potatoes, halved",
      "1 bunch asparagus, trimmed",
      "3 tbsp olive oil",
      "2 lemons, one sliced and one for juice",
      "3 garlic cloves, minced",
      "1 tbsp fresh dill (or 1 tsp dried)",
      "Salt, pepper"
    ],
    "steps": [
      "Oven 425F. Toss potatoes with olive oil, salt, pepper, roast 15 min.",
      "Push potatoes to one side, add asparagus and salmon.",
      "Brush salmon with oil, garlic, dill, top with lemon slices.",
      "Roast 12-14 min until salmon flakes (145F internal).",
      "Finish with fresh lemon juice."
    ],
    "notes": null
  },
  {
    "slug": "sheet-pan-chicken-fajitas",
    "name": "Sheet Pan Chicken Fajitas",
    "category": "dinner",
    "tool": "Sheet Pan",
    "proteinGrams": 40,
    "servings": 4,
    "prepMin": 15,
    "cookMin": 25,
    "tags": [
      "Sheet Pan",
      "High Protein",
      "Mexican",
      "Dinner"
    ],
    "ingredients": [
      "1.5 lb chicken breast, sliced",
      "3 bell peppers (mixed colors), sliced",
      "1 large red onion, sliced",
      "3 tbsp olive oil",
      "2 tbsp fajita seasoning (or chili powder + cumin + garlic + paprika mix)",
      "Juice of 1 lime",
      "Flour tortillas",
      "Toppings: sour cream, shredded cheese, cilantro, lime"
    ],
    "steps": [
      "Oven 425F. Toss chicken, peppers, onion with oil and seasoning on sheet pan.",
      "Roast 20-25 min, tossing halfway, until chicken is 165F.",
      "Squeeze lime over top, serve with warm tortillas and toppings."
    ],
    "notes": null
  },
  {
    "slug": "greek-chicken-thighs-with-lemon-potatoes",
    "name": "Greek Chicken Thighs with Lemon Potatoes",
    "category": "dinner",
    "tool": "Sheet Pan",
    "proteinGrams": 44,
    "servings": 4,
    "prepMin": 15,
    "cookMin": 45,
    "tags": [
      "Sheet Pan",
      "High Protein",
      "Mediterranean",
      "Dinner"
    ],
    "ingredients": [
      "8 bone-in skin-on chicken thighs",
      "1.5 lb baby gold potatoes, halved",
      "1/4 cup olive oil",
      "1/4 cup lemon juice",
      "4 garlic cloves, minced",
      "1 tbsp dried oregano",
      "1 tsp salt, pepper",
      "1/2 cup feta (pasteurized)",
      "Kalamata olives, chopped parsley",
      "Cucumber tomato salad on the side"
    ],
    "steps": [
      "Whisk oil, lemon, garlic, oregano, salt. Marinate chicken 15 min+.",
      "Oven 425F. Arrange chicken and potatoes on sheet pan, pour marinade over.",
      "Roast 40-45 min, until chicken 175F and potatoes crispy.",
      "Top with feta, olives, parsley."
    ],
    "notes": null
  },
  {
    "slug": "air-fryer-chicken-parmesan",
    "name": "Air Fryer Chicken Parmesan",
    "category": "dinner",
    "tool": "Air Fryer + Sauté",
    "proteinGrams": 48,
    "servings": 4,
    "prepMin": 15,
    "cookMin": 20,
    "tags": [
      "Air Fryer",
      "Sauté",
      "High Protein",
      "Italian",
      "Dinner"
    ],
    "ingredients": [
      "4 chicken breast cutlets (or butterfly 2 breasts)",
      "1 cup panko breadcrumbs",
      "1/2 cup grated parmesan (pasteurized)",
      "1 tsp Italian seasoning",
      "2 eggs, beaten",
      "1/2 cup flour",
      "1.5 cups marinara sauce",
      "1 cup shredded mozzarella (pasteurized)",
      "12 oz whole wheat pasta or zucchini noodles",
      "Fresh basil"
    ],
    "steps": [
      "Dredge chicken in flour, then egg, then panko mixed with parmesan and seasoning.",
      "Air fry 400F for 10 min, flip, spoon marinara, add mozzarella, air fry 4 more min.",
      "Cook pasta according to package, toss with a little marinara.",
      "Serve chicken over pasta with basil."
    ],
    "notes": null
  },
  {
    "slug": "air-fryer-turkey-meatballs-with-pasta",
    "name": "Air Fryer Turkey Meatballs with Pasta",
    "category": "dinner",
    "tool": "Air Fryer",
    "proteinGrams": 42,
    "servings": 5,
    "prepMin": 15,
    "cookMin": 15,
    "tags": [
      "Air Fryer",
      "Freezer Friendly",
      "High Protein",
      "Quick",
      "Italian",
      "Dinner"
    ],
    "ingredients": [
      "1.5 lb ground turkey (93/7)",
      "1/2 cup panko",
      "1/3 cup milk",
      "1/4 cup grated parmesan",
      "1 egg",
      "3 garlic cloves, minced",
      "2 tbsp fresh parsley",
      "1 tsp salt, 1/2 tsp pepper, 1/2 tsp Italian seasoning",
      "24 oz marinara sauce",
      "12 oz rigatoni or penne",
      "Fresh basil, extra parmesan"
    ],
    "steps": [
      "Mix turkey with panko, milk, parmesan, egg, garlic, parsley, seasoning.",
      "Roll into 1.5 inch balls (about 20). Freeze half raw for backup night.",
      "Air fry at 400F for 10-12 min until 165F internal.",
      "Simmer in marinara 5 min, serve over pasta with basil and parmesan."
    ],
    "notes": null
  },
  {
    "slug": "ground-turkey-taco-skillet",
    "name": "Ground Turkey Taco Skillet",
    "category": "dinner",
    "tool": "Sauté",
    "proteinGrams": 38,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 20,
    "tags": [
      "Sauté",
      "Skillet",
      "High Protein",
      "Quick",
      "Mexican",
      "Dinner"
    ],
    "ingredients": [
      "1.25 lb ground turkey (93/7)",
      "1 tbsp olive oil",
      "1 onion, diced, 1 bell pepper, diced",
      "2 tbsp taco seasoning",
      "1 can diced tomatoes with green chiles",
      "1 cup cooked rice (or quinoa)",
      "1 can black beans, drained",
      "1 cup frozen corn",
      "1 cup shredded cheddar",
      "Greek yogurt, avocado, cilantro, lime to top"
    ],
    "steps": [
      "Heat oil, sauté onion and pepper 5 min.",
      "Add turkey, brown and break up, 6 min.",
      "Stir in seasoning, tomatoes, rice, beans, corn. Simmer 8 min.",
      "Top with cheese, cover off heat to melt.",
      "Serve with yogurt, avocado, cilantro, lime."
    ],
    "notes": null
  },
  {
    "slug": "shrimp-and-sausage-skillet",
    "name": "Shrimp and Sausage Skillet",
    "category": "dinner",
    "tool": "Sauté",
    "proteinGrams": 40,
    "servings": 4,
    "prepMin": 10,
    "cookMin": 20,
    "tags": [
      "Sauté",
      "Skillet",
      "High Protein",
      "Quick",
      "Dinner"
    ],
    "ingredients": [
      "1 lb large shrimp, peeled deveined",
      "12 oz fully cooked andouille or chicken sausage, sliced",
      "2 tbsp olive oil",
      "1 onion, diced, 2 bell peppers, sliced",
      "3 garlic cloves, minced",
      "1 tsp smoked paprika, 1 tsp Cajun seasoning",
      "1 can diced tomatoes",
      "2 cups cooked rice or cauliflower rice",
      "Green onions, parsley"
    ],
    "steps": [
      "Heat oil, brown sausage 4 min, remove.",
      "Sauté onion and peppers 5 min, add garlic and spices 30 sec.",
      "Add tomatoes, simmer 5 min. Return sausage, add shrimp.",
      "Cook 3-4 min until shrimp is pink and firm (145F).",
      "Serve over rice with green onions and parsley."
    ],
    "notes": null
  },
  {
    "slug": "stuffed-peppers-with-turkey-and-quinoa",
    "name": "Stuffed Peppers with Turkey and Quinoa",
    "category": "dinner",
    "tool": "Oven + Sauté",
    "proteinGrams": 37,
    "servings": 5,
    "prepMin": 20,
    "cookMin": 40,
    "tags": [
      "Oven",
      "Sauté",
      "Freezer Friendly",
      "High Protein",
      "Italian",
      "Iron Rich",
      "Dinner"
    ],
    "ingredients": [
      "5 large bell peppers, tops cut off and seeded",
      "1.25 lb ground turkey",
      "1 tbsp olive oil",
      "1 onion, diced, 3 garlic cloves, minced",
      "1 tsp Italian seasoning, 1 tsp salt, 1/2 tsp pepper",
      "1 can (15 oz) fire roasted diced tomatoes",
      "1.5 cups cooked quinoa",
      "1 can spinach or 3 cups fresh baby spinach, chopped",
      "1.5 cups shredded mozzarella",
      "1/4 cup grated parmesan",
      "1 cup marinara for the baking dish"
    ],
    "steps": [
      "Oven 375F. Par-cook pepper shells in boiling water 4 min, drain.",
      "Sauté onion in oil, add turkey and brown, add garlic and seasoning.",
      "Stir in tomatoes, quinoa, spinach. Cook 3 min.",
      "Spread marinara in baking dish, stand peppers up, stuff generously.",
      "Top with mozzarella and parmesan. Bake 25 min until bubbly.",
      "Freeze one pepper per person as designated backup meal if desired."
    ],
    "notes": null
  },
  {
    "slug": "chicken-dump-soup",
    "name": "Chicken Dump Soup",
    "category": "soup",
    "tool": "Instant Pot",
    "proteinGrams": 34,
    "servings": 6,
    "prepMin": 5,
    "cookMin": 35,
    "tags": [
      "Instant Pot",
      "Dump and Go",
      "Freezer Backup",
      "High Protein",
      "Italian",
      "Iron Rich",
      "Soup"
    ],
    "ingredients": [
      "1.5 lb chicken breast or thighs",
      "6 cups low sodium chicken broth",
      "1 onion, diced",
      "3 carrots, sliced",
      "3 celery stalks, sliced",
      "1 can diced tomatoes",
      "1 can white beans, drained",
      "3 cups baby spinach (added at end)",
      "1 tsp Italian seasoning, 1 tsp garlic powder, salt, pepper",
      "1.5 cups cooked orzo or rice (add at end)",
      "Parmesan rind (optional but great)"
    ],
    "steps": [
      "Dump everything except spinach and orzo into Instant Pot.",
      "Pressure cook High 15 min, natural release 10 min.",
      "Shred chicken in pot. Stir in cooked orzo and spinach until wilted.",
      "Taste for salt. Freezes great (freeze without pasta, add fresh when reheating)."
    ],
    "notes": null
  },
  {
    "slug": "italian-wedding-soup",
    "name": "Italian Wedding Soup",
    "category": "soup",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 32,
    "servings": 6,
    "prepMin": 20,
    "cookMin": 25,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Comfort",
      "High Protein",
      "Italian",
      "Iron Rich",
      "Soup"
    ],
    "ingredients": [
      "1 lb ground turkey or chicken",
      "1/3 cup panko, 1 egg, 1/4 cup parmesan, 2 garlic cloves minced, 1 tsp Italian seasoning",
      "1 tbsp olive oil",
      "1 onion, 2 carrots, 2 celery stalks, all diced",
      "8 cups chicken broth",
      "1 cup acini de pepe or orzo",
      "4 cups chopped escarole, kale, or baby spinach",
      "Parmesan and lemon to finish"
    ],
    "steps": [
      "Mix meatball ingredients, roll into tiny 3/4 inch balls.",
      "Sauté in Instant Pot to brown lightly, remove. Sauté aromatics 5 min.",
      "Add broth, return meatballs, pressure cook High 5 min, quick release.",
      "Stir in pasta on Sauté mode 8 min until cooked.",
      "Add greens, stir until wilted. Top with parmesan and lemon."
    ],
    "notes": null
  },
  {
    "slug": "red-lentil-soup",
    "name": "Red Lentil Soup",
    "category": "soup",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 22,
    "servings": 6,
    "prepMin": 10,
    "cookMin": 25,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Iron Rich",
      "Vegetarian",
      "Soup"
    ],
    "ingredients": [
      "2 tbsp olive oil",
      "1 onion, diced, 2 carrots diced, 4 garlic cloves minced",
      "2 tbsp tomato paste",
      "1.5 tbsp cumin, 1 tsp smoked paprika, 1/2 tsp turmeric, pinch cayenne",
      "1.5 cups red lentils, rinsed",
      "6 cups vegetable or chicken broth",
      "1 can diced tomatoes",
      "Juice of 1 lemon",
      "4 cups baby spinach",
      "Plain Greek yogurt, parsley, olive oil to serve"
    ],
    "steps": [
      "Sauté onion and carrots in oil 5 min, add garlic and spices 1 min.",
      "Stir in tomato paste 1 min, then lentils, broth, and tomatoes.",
      "Pressure cook High 8 min, natural release 10 min.",
      "Stir in spinach and lemon. Blend partially with immersion blender if you like.",
      "Top with yogurt, parsley, drizzle olive oil."
    ],
    "notes": null
  },
  {
    "slug": "white-bean-and-kale-soup-with-sausage",
    "name": "White Bean and Kale Soup with Sausage",
    "category": "soup",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 28,
    "servings": 6,
    "prepMin": 10,
    "cookMin": 25,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Hearty",
      "Italian",
      "Soup"
    ],
    "ingredients": [
      "12 oz fully cooked chicken Italian sausage, sliced",
      "2 tbsp olive oil",
      "1 onion, 2 carrots, 2 celery stalks, all diced",
      "4 garlic cloves, minced",
      "1 tsp Italian seasoning, pinch red pepper flakes",
      "6 cups chicken broth",
      "2 cans cannellini beans, drained",
      "1 parmesan rind",
      "4 cups chopped lacinato kale",
      "Lemon juice, parmesan to finish"
    ],
    "steps": [
      "Sauté sausage to brown, remove. Sauté aromatics 6 min with seasoning.",
      "Add broth, beans, rind. Pressure cook High 6 min, quick release.",
      "Return sausage, stir in kale until wilted.",
      "Finish with lemon and parmesan."
    ],
    "notes": null
  },
  {
    "slug": "beef-and-barley-soup",
    "name": "Beef and Barley Soup",
    "category": "soup",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 35,
    "servings": 6,
    "prepMin": 15,
    "cookMin": 50,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Iron Rich",
      "High Protein",
      "Soup"
    ],
    "ingredients": [
      "1.5 lb beef stew meat, cut into 1 inch cubes",
      "2 tbsp olive oil",
      "1 onion, 2 carrots, 2 celery stalks, 8 oz mushrooms, all diced",
      "3 garlic cloves minced",
      "2 tbsp tomato paste",
      "1 cup pearl barley",
      "7 cups beef broth",
      "2 tbsp Worcestershire",
      "1 tsp thyme, 2 bay leaves",
      "2 cups chopped kale or spinach",
      "Salt, pepper, fresh parsley"
    ],
    "steps": [
      "Season beef. Sauté in Instant Pot with oil to brown 5 min, remove.",
      "Sauté vegetables 6 min, add garlic and tomato paste 1 min.",
      "Return beef, add barley, broth, Worcestershire, thyme, bay leaves.",
      "Pressure cook High 30 min, natural release 15 min.",
      "Stir in kale, remove bay. Parsley to finish."
    ],
    "notes": null
  },
  {
    "slug": "chicken-tortilla-soup",
    "name": "Chicken Tortilla Soup",
    "category": "soup",
    "tool": "Instant Pot + Sauté",
    "proteinGrams": 35,
    "servings": 6,
    "prepMin": 10,
    "cookMin": 25,
    "tags": [
      "Instant Pot",
      "Sauté",
      "Dump and Go",
      "High Protein",
      "Mexican",
      "Soup"
    ],
    "ingredients": [
      "1.25 lb chicken breast",
      "1 tbsp olive oil",
      "1 onion, 1 bell pepper, 4 garlic cloves",
      "1 tbsp chili powder, 2 tsp cumin, 1 tsp smoked paprika, 1 tsp oregano",
      "1 can fire roasted tomatoes, 1 can black beans drained, 1 can corn drained",
      "1 can green chiles",
      "5 cups chicken broth",
      "Juice of 1 lime",
      "Tortilla strips (baked), avocado, cilantro, Monterey Jack, Greek yogurt"
    ],
    "steps": [
      "Sauté onion and pepper 4 min, add garlic and spices 1 min.",
      "Add everything else except toppings. Pressure cook High 12 min, natural release 10 min.",
      "Shred chicken in pot, add lime.",
      "Serve with strips, avocado, cilantro, cheese, yogurt dollop."
    ],
    "notes": null
  },
  {
    "slug": "veggie-egg-muffins",
    "name": "Veggie Egg Muffins",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 24,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Iron Rich",
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "10 eggs",
      "1 cup cottage cheese",
      "1 cup chopped spinach",
      "1/2 cup diced bell pepper",
      "1/2 cup diced ham or turkey sausage",
      "1/2 cup shredded cheddar",
      "salt pepper"
    ],
    "steps": [
      "Whisk eggs and cottage cheese.",
      "Divide fillings into greased muffin tin.",
      "Pour egg over.",
      "Bake 375F for 22 min."
    ],
    "notes": "Make 12 on Sunday, eat 3 per person per morning for 2 days"
  },
  {
    "slug": "protein-overnight-oats",
    "name": "Protein Overnight Oats",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 32,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Omega-3",
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "1/2 cup rolled oats",
      "1 scoop whey or plant protein",
      "1 cup milk",
      "2 tbsp chia seeds",
      "2 tbsp peanut butter",
      "1 tbsp maple",
      "1/2 banana sliced",
      "berries"
    ],
    "steps": [
      "Layer in mason jar, shake, refrigerate overnight.",
      "Top with fruit and nuts in the morning."
    ],
    "notes": "Assemble 4 jars Sunday, last 4 days in fridge"
  },
  {
    "slug": "greek-yogurt-parfait",
    "name": "Greek Yogurt Parfait",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 28,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Omega-3",
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "1 cup full-fat plain Greek yogurt",
      "1/4 cup granola",
      "1/2 cup berries",
      "2 tbsp chopped almonds",
      "1 tsp honey",
      "chia seeds"
    ],
    "steps": [
      "Layer yogurt, fruit, granola, nuts.",
      "Drizzle honey."
    ],
    "notes": "Build each morning in under 3 min"
  },
  {
    "slug": "make-ahead-breakfast-burritos",
    "name": "Make-Ahead Breakfast Burritos",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 30,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Mexican",
      "Make Ahead",
      "Freezer Friendly",
      "Breakfast"
    ],
    "ingredients": [
      "6 large whole wheat tortillas",
      "10 eggs scrambled",
      "1 can black beans",
      "12 oz cooked turkey sausage or chorizo",
      "1.5 cups shredded cheese",
      "salsa"
    ],
    "steps": [
      "Scramble eggs, cook sausage.",
      "Build each burrito with eggs, sausage, beans, cheese, salsa.",
      "Wrap in foil, freeze.",
      "Reheat in microwave 2 min then 30 sec per side, or air fryer 350F 8 min."
    ],
    "notes": "Make 6 Sunday, freeze individually wrapped"
  },
  {
    "slug": "cottage-cheese-toast",
    "name": "Cottage Cheese Toast",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 26,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "2 slices whole grain sourdough toast",
      "1 cup full-fat cottage cheese",
      "sliced tomato or cucumber",
      "everything bagel seasoning",
      "1 sliced hard boiled egg"
    ],
    "steps": [
      "Toast bread.",
      "Spread cottage cheese thick.",
      "Top with veg, egg, seasoning."
    ],
    "notes": "Assemble fresh, under 5 min"
  },
  {
    "slug": "power-protein-smoothie",
    "name": "Power Protein Smoothie",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 35,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Omega-3",
      "Iron Rich",
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "1 scoop whey or collagen",
      "1 cup milk",
      "1/2 cup Greek yogurt",
      "1 frozen banana",
      "1 cup frozen berries",
      "1 tbsp peanut butter",
      "1 tbsp chia seeds",
      "handful spinach"
    ],
    "steps": [
      "Blend all until smooth.",
      "Drink immediately or pour into insulated cup."
    ],
    "notes": "Blend fresh, under 5 min"
  },
  {
    "slug": "chia-pudding-jars",
    "name": "Chia Pudding Jars",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 20,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Omega-3",
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "1/4 cup chia seeds + 1 cup milk + 1 scoop vanilla protein + 1 tbsp maple per jar. Top with berries and sliced almonds."
    ],
    "steps": [
      "Whisk chia, milk, protein.",
      "Refrigerate overnight.",
      "Top in morning."
    ],
    "notes": "Make 4 jars Sunday, last 5 days"
  },
  {
    "slug": "sheet-pan-pancakes",
    "name": "Sheet Pan Pancakes",
    "category": "breakfast",
    "tool": null,
    "proteinGrams": 22,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Make Ahead",
      "Breakfast"
    ],
    "ingredients": [
      "2 boxes Kodiak Cakes mix (or protein pancake mix) per instructions",
      "2 cups blueberries scattered on top",
      "cinnamon"
    ],
    "steps": [
      "Pour batter on greased sheet pan, scatter berries, bake 425F for 13-15 min.",
      "Cut into squares.",
      "Reheat in toaster or air fryer."
    ],
    "notes": "Make Sunday, reheat in toaster"
  },
  {
    "slug": "leftover-dinner",
    "name": "Leftover Dinner",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 0,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Pack next-day lunches from every dinner cooked at 4+ servings. Covers 3-4 lunches per week each."
  },
  {
    "slug": "mediterranean-chicken-wrap",
    "name": "Mediterranean Chicken Wrap",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 35,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Mexican",
      "Iron Rich",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Uses reusable shredded chicken. Large spinach tortilla, hummus, shredded chicken, cucumber, tomato, red onion, feta (pasteurized), kalamata olives, tzatziki."
  },
  {
    "slug": "buffalo-chicken-wrap",
    "name": "Buffalo Chicken Wrap",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 38,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Mexican",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Uses reusable shredded chicken. Tortilla, buffalo-sauced chicken, romaine, diced celery, blue cheese or ranch, shredded carrots."
  },
  {
    "slug": "chicken-caesar-wrap",
    "name": "Chicken Caesar Wrap",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 36,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Mexican",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Uses reusable shredded chicken. Tortilla, chicken tossed in caesar, chopped romaine, parmesan, croutons optional."
  },
  {
    "slug": "southwest-quinoa-power-bowl",
    "name": "Southwest Quinoa Power Bowl",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 26,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Cooked quinoa base, black beans, corn, diced bell pepper, cherry tomatoes, avocado, cilantro lime dressing, pumpkin seeds. Add grilled chicken for 40g."
  },
  {
    "slug": "mason-jar-cobb-salad",
    "name": "Mason Jar Cobb Salad",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 34,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Layer: dressing, cherry tomatoes, cucumber, chickpeas, hard boiled egg slices, shredded chicken, bacon bits, blue cheese, chopped romaine on top. Shake and dump when eating."
  },
  {
    "slug": "turkey-and-hummus-wrap",
    "name": "Turkey and Hummus Wrap",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 30,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Mexican",
      "Iron Rich",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Whole wheat tortilla, hummus base, WELL HEATED sliced turkey (microwave 30 sec to steaming to be safe), spinach, cucumber, shredded carrot, feta. Listeria note: always heat deli meat through during pregnancy."
  },
  {
    "slug": "tuna-salad-on-whole-grain",
    "name": "Tuna Salad on Whole Grain",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 32,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "High Protein",
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "Canned light tuna (limit to 2-3 servings/week for mercury), Greek yogurt mayo mix, celery, red onion, dill, lemon. Open face on sourdough with lettuce and tomato."
  },
  {
    "slug": "cottage-cheese-bowl",
    "name": "Cottage Cheese Bowl",
    "category": "lunch",
    "tool": null,
    "proteinGrams": 28,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Lunch"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1.5 cups cottage cheese, diced cucumber, cherry tomatoes, everything seasoning, avocado, hemp seeds. Savory version of a yogurt bowl."
  },
  {
    "slug": "hard-boiled-eggs",
    "name": "Hard boiled eggs",
    "category": "snack",
    "tool": null,
    "proteinGrams": 12,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "2 eggs, everything bagel seasoning"
  },
  {
    "slug": "apple-with-peanut-butter",
    "name": "Apple with peanut butter",
    "category": "snack",
    "tool": null,
    "proteinGrams": 8,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 apple, 2 tbsp PB"
  },
  {
    "slug": "greek-yogurt-granola",
    "name": "Greek yogurt + granola",
    "category": "snack",
    "tool": null,
    "proteinGrams": 22,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 cup full-fat Greek yogurt, granola, honey"
  },
  {
    "slug": "cottage-cheese-fruit",
    "name": "Cottage cheese + fruit",
    "category": "snack",
    "tool": null,
    "proteinGrams": 18,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 cup cottage cheese, peaches or pineapple"
  },
  {
    "slug": "cheese-whole-grain-crackers",
    "name": "Cheese + whole grain crackers",
    "category": "snack",
    "tool": null,
    "proteinGrams": 12,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "2 oz cheddar or gouda (pasteurized), 10 crackers"
  },
  {
    "slug": "edamame",
    "name": "Edamame",
    "category": "snack",
    "tool": null,
    "proteinGrams": 17,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 cup shelled, sea salt"
  },
  {
    "slug": "roasted-chickpeas",
    "name": "Roasted chickpeas",
    "category": "snack",
    "tool": null,
    "proteinGrams": 10,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1/2 cup, seasoned how you like"
  },
  {
    "slug": "turkey-and-cheese-rollups",
    "name": "Turkey and cheese rollups",
    "category": "snack",
    "tool": null,
    "proteinGrams": 18,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "HEATED turkey slices wrapped around cheese sticks"
  },
  {
    "slug": "almonds-dried-apricots",
    "name": "Almonds + dried apricots",
    "category": "snack",
    "tool": null,
    "proteinGrams": 8,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Iron Rich",
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1/4 cup almonds, handful apricots (iron!)"
  },
  {
    "slug": "smoothie-with-protein-powder",
    "name": "Smoothie with protein powder",
    "category": "snack",
    "tool": null,
    "proteinGrams": 25,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "milk, frozen berries, banana, scoop protein"
  },
  {
    "slug": "oatmeal-with-pb-and-banana",
    "name": "Oatmeal with PB and banana",
    "category": "snack",
    "tool": null,
    "proteinGrams": 12,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1/2 cup oats, PB, banana, milk"
  },
  {
    "slug": "hummus-carrots-and-pepper-strips",
    "name": "Hummus + carrots and pepper strips",
    "category": "snack",
    "tool": null,
    "proteinGrams": 8,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Mediterranean",
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1/2 cup hummus, fresh veg"
  },
  {
    "slug": "tuna-packet-crackers",
    "name": "Tuna packet + crackers",
    "category": "snack",
    "tool": null,
    "proteinGrams": 22,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 tuna packet, whole grain crackers (limit 2x/week)"
  },
  {
    "slug": "deviled-eggs",
    "name": "Deviled eggs",
    "category": "snack",
    "tool": null,
    "proteinGrams": 14,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "2 halves with Greek yogurt instead of mayo"
  },
  {
    "slug": "avocado-toast-with-egg",
    "name": "Avocado toast with egg",
    "category": "snack",
    "tool": null,
    "proteinGrams": 20,
    "servings": null,
    "prepMin": null,
    "cookMin": null,
    "tags": [
      "Snack"
    ],
    "ingredients": [],
    "steps": [],
    "notes": "1 slice sourdough, avocado, 1 fried egg"
  }
];
