// GENERATED by scripts/extract.py. Do not edit by hand.
import type { ShoppingWeek } from "./types";

export const shopping: ShoppingWeek[] = [
  {
    "week": 0,
    "dateLabel": "Buy once for the month — bulk-friendly items used across multiple weeks",
    "sections": [
      {
        "name": "Proteins (freeze portions)",
        "items": [
          {
            "name": "Boneless skinless chicken thighs",
            "qty": "6 lb (split into 2 freezer bags)",
            "for": "Week 1 + Week 4 Instant Pot batches"
          },
          {
            "name": "Ground turkey (93/7)",
            "qty": "6 lb (split into ~1.25 lb portions)",
            "for": "Stuffed peppers + meatballs + taco skillet across Weeks 2–5"
          },
          {
            "name": "Boneless pork shoulder",
            "qty": "7 lb (one chunk per pulled pork batch)",
            "for": "Week 3 + Week 5 Instant Pot pulled pork"
          },
          {
            "name": "Salmon fillets (6 oz, individually frozen)",
            "qty": "8",
            "for": "Week 2 + Week 4 sheet pan salmon"
          },
          {
            "name": "Chicken breast",
            "qty": "3 lb",
            "for": "Fajitas + tortilla soup + dump soup"
          },
          {
            "name": "Chicken cutlets",
            "qty": "4 lb (freeze in pairs)",
            "for": "Week 3 + Week 5 chicken parm"
          },
          {
            "name": "Bone-in skin-on chicken thighs",
            "qty": "16 (2 packs)",
            "for": "Week 2 + Week 5 Greek chicken"
          }
        ]
      },
      {
        "name": "Pantry / Dry (long shelf)",
        "items": [
          {
            "name": "Rolled oats",
            "qty": "large canister",
            "for": "Overnight oats every week"
          },
          {
            "name": "Chia seeds",
            "qty": "1 lb bag",
            "for": "Overnight oats + chia pudding + smoothies"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "1 large tub",
            "for": "Smoothie + overnight oats every week"
          },
          {
            "name": "Peanut butter",
            "qty": "large jar",
            "for": "Snacks + overnight oats + smoothie"
          },
          {
            "name": "Granola",
            "qty": "large bag",
            "for": "Yogurt parfaits"
          },
          {
            "name": "Quinoa",
            "qty": "2 lb bag",
            "for": "Stuffed peppers + power bowls"
          },
          {
            "name": "Rice (jasmine or long grain)",
            "qty": "5 lb bag",
            "for": "Skillets + bowls"
          },
          {
            "name": "Pearl barley",
            "qty": "1 lb bag",
            "for": "Beef and barley soup"
          },
          {
            "name": "Red lentils",
            "qty": "1 lb bag",
            "for": "Red lentil soup"
          },
          {
            "name": "Pasta (rigatoni or penne)",
            "qty": "2 boxes",
            "for": "Meatballs + chicken parm"
          },
          {
            "name": "Whole wheat pasta",
            "qty": "2 boxes",
            "for": "Chicken parm Weeks 3 + 5"
          },
          {
            "name": "Acini de pepe or orzo",
            "qty": "1 box",
            "for": "Wedding soup + dump soup"
          },
          {
            "name": "Small corn tortillas",
            "qty": "4 dozen",
            "for": "Tacos + enchilada skillet"
          },
          {
            "name": "Flour tortillas (taco/fajita size)",
            "qty": "2 packs",
            "for": "Fajitas + barbacoa"
          },
          {
            "name": "Large flour tortillas (burrito size)",
            "qty": "2 packs (12 ct)",
            "for": "Breakfast burritos"
          },
          {
            "name": "Brioche or hamburger buns",
            "qty": "2 packs",
            "for": "BBQ pulled pork sandwiches"
          },
          {
            "name": "Panko breadcrumbs",
            "qty": "large box",
            "for": "Egg muffins + meatballs + chicken parm"
          },
          {
            "name": "Black beans (canned)",
            "qty": "8 cans",
            "for": "Tacos, skillets, bowls, tortilla soup"
          },
          {
            "name": "Cannellini / white beans (canned)",
            "qty": "4 cans",
            "for": "Dump soup + white bean soup"
          },
          {
            "name": "Diced tomatoes (canned)",
            "qty": "4 cans",
            "for": "Skillets + soups"
          },
          {
            "name": "Fire roasted diced tomatoes",
            "qty": "4 cans",
            "for": "Stuffed peppers + tortilla soup"
          },
          {
            "name": "Diced tomatoes with green chiles",
            "qty": "3 cans",
            "for": "Taco skillet + tortilla soup"
          },
          {
            "name": "Tomato paste (tube or small cans)",
            "qty": "1 tube + 2 cans",
            "for": "Beef barley + red lentil"
          },
          {
            "name": "Marinara sauce",
            "qty": "2 large jars (48 oz total)",
            "for": "Chicken parm + meatballs + stuffed peppers"
          },
          {
            "name": "Red enchilada sauce",
            "qty": "2 cans (28 oz total)",
            "for": "Enchilada skillet Weeks 1 + 4"
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "2 large jars (32 oz total)",
            "for": "Tacos + burritos + bowls + skillets"
          },
          {
            "name": "BBQ sauce",
            "qty": "1 large bottle",
            "for": "Pulled pork Weeks 3 + 5"
          },
          {
            "name": "Apple cider vinegar",
            "qty": "1 bottle",
            "for": "Pulled pork brine + slaw dressing"
          },
          {
            "name": "Worcestershire sauce",
            "qty": "1 bottle",
            "for": "Beef barley + pot roast"
          },
          {
            "name": "Frank's RedHot (or buffalo sauce)",
            "qty": "1 bottle",
            "for": "Buffalo sweet potatoes + buffalo wraps"
          },
          {
            "name": "Low sodium chicken broth",
            "qty": "8 quarts (carton 4-pack x 2)",
            "for": "Soups every week"
          },
          {
            "name": "Beef broth",
            "qty": "2 quarts",
            "for": "Pot roast + beef barley"
          },
          {
            "name": "Olive oil",
            "qty": "large bottle",
            "for": "Cooking + dressings"
          },
          {
            "name": "Spice basics",
            "qty": "as needed",
            "for": "Chili powder, cumin, smoked paprika, oregano, Italian seasoning, taco seasoning, fajita seasoning, garlic + onion powder, thyme, bay leaves"
          },
          {
            "name": "Brown sugar + flour",
            "qty": "small bags",
            "for": "Pulled pork rub + chicken parm dredge"
          }
        ]
      },
      {
        "name": "Dairy / Bulk",
        "items": [
          {
            "name": "Plain Greek yogurt (full fat)",
            "qty": "Costco tub (32 oz x 2)",
            "for": "Breakfasts + sauces every week"
          },
          {
            "name": "Cottage cheese (full fat)",
            "qty": "Costco tub",
            "for": "Egg muffins + breakfasts"
          },
          {
            "name": "Butter",
            "qty": "1 lb (4 sticks)",
            "for": "Pot roast + buffalo sweet potatoes + cooking"
          },
          {
            "name": "Parmesan (grated, pasteurized)",
            "qty": "Costco tub",
            "for": "Chicken parm + meatballs + soups"
          },
          {
            "name": "Mozzarella shredded (pasteurized)",
            "qty": "2 lb bag",
            "for": "Stuffed peppers + chicken parm"
          },
          {
            "name": "Shredded Monterey Jack (pasteurized)",
            "qty": "2 lb bag",
            "for": "Enchilada skillet + tortilla soup + tacos"
          },
          {
            "name": "Shredded cheddar (pasteurized)",
            "qty": "2 lb bag",
            "for": "Egg muffins + taco skillets"
          }
        ]
      },
      {
        "name": "Frozen",
        "items": [
          {
            "name": "Frozen mixed berries",
            "qty": "Costco bag (4 lb)",
            "for": "Smoothies + parfaits + oats every week"
          },
          {
            "name": "Frozen corn",
            "qty": "2 large bags",
            "for": "Skillets + soups"
          },
          {
            "name": "Frozen shelled edamame",
            "qty": "1 large bag",
            "for": "Snacks"
          }
        ]
      },
      {
        "name": "Snack Stocking",
        "items": [
          {
            "name": "Almonds",
            "qty": "Costco bag",
            "for": "Snacks + parfaits"
          },
          {
            "name": "Dried apricots",
            "qty": "1 large bag",
            "for": "Iron-rich snack"
          },
          {
            "name": "Whole grain crackers",
            "qty": "Costco box",
            "for": "Cheese snacks + tuna"
          },
          {
            "name": "Hummus",
            "qty": "Costco 2-pack",
            "for": "Snacks + wraps"
          },
          {
            "name": "String cheese (pasteurized)",
            "qty": "Costco pack",
            "for": "Snacks + rollups"
          }
        ]
      }
    ]
  },
  {
    "week": 1,
    "dateLabel": "Sun Apr 26 - Sat May 2",
    "sections": [
      {
        "name": "Proteins",
        "items": [
          {
            "name": "Boneless skinless chicken thighs (big batch Instant Pot)",
            "qty": "3 lb",
            "for": "Fri: Shredded chicken tacos, Sat: Enchilada skillet"
          }
        ]
      },
      {
        "name": "Produce",
        "items": [
          {
            "name": "Yellow onions",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Red bell peppers",
            "qty": "2",
            "for": "Enchilada skillet + Sat toppings"
          },
          {
            "name": "Limes",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Cilantro",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Avocados",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Roma tomatoes",
            "qty": "4",
            "for": "Pico and toppings"
          },
          {
            "name": "Garlic head",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Baby spinach",
            "qty": "5 oz",
            "for": "Egg muffins"
          },
          {
            "name": "Green onions",
            "qty": "1 bunch",
            "for": "Enchilada skillet garnish"
          }
        ]
      },
      {
        "name": "Dairy / Refrigerated",
        "items": [
          {
            "name": "Queso fresco (pasteurized)",
            "qty": "8 oz",
            "for": ""
          },
          {
            "name": "Shredded Monterey Jack (pasteurized)",
            "qty": "8 oz",
            "for": ""
          },
          {
            "name": "Shredded cheddar (pasteurized)",
            "qty": "8 oz",
            "for": "Egg muffins"
          },
          {
            "name": "Diced ham or breakfast turkey sausage",
            "qty": "8 oz",
            "for": "Egg muffins filling"
          },
          {
            "name": "Plain Greek yogurt (full fat)",
            "qty": "32 oz",
            "for": "Breakfast + snacks"
          },
          {
            "name": "Cottage cheese (full fat)",
            "qty": "16 oz",
            "for": "Breakfast + snacks"
          },
          {
            "name": "Whole milk",
            "qty": "1/2 gal",
            "for": ""
          },
          {
            "name": "Large eggs",
            "qty": "2 dozen",
            "for": "Egg muffins + breakfasts"
          },
          {
            "name": "Butter",
            "qty": "1 stick",
            "for": ""
          }
        ]
      },
      {
        "name": "Pantry / Dry",
        "items": [
          {
            "name": "Small corn tortillas",
            "qty": "2 dozen",
            "for": ""
          },
          {
            "name": "Low sodium chicken broth",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Black beans (canned)",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Red enchilada sauce",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Panko breadcrumbs",
            "qty": "small box",
            "for": "Egg muffins"
          },
          {
            "name": "Rolled oats",
            "qty": "1 lb",
            "for": "Breakfast"
          },
          {
            "name": "Chia seeds",
            "qty": "1 bag",
            "for": "Breakfast"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "1 tub",
            "for": "If needed for smoothie or overnight oats"
          },
          {
            "name": "Peanut butter",
            "qty": "1 jar",
            "for": "Snacks + overnight oats"
          },
          {
            "name": "Granola",
            "qty": "1 bag",
            "for": "Parfaits"
          },
          {
            "name": "Spices: chili powder, cumin, smoked paprika, oregano, Italian seasoning",
            "qty": "as needed",
            "for": ""
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "16 oz jar",
            "for": "Tacos Fri + enchilada skillet Sat"
          }
        ]
      },
      {
        "name": "Frozen / Misc",
        "items": [
          {
            "name": "Frozen corn",
            "qty": "1 bag",
            "for": "Enchilada skillet"
          },
          {
            "name": "Frozen mixed berries",
            "qty": "1 bag",
            "for": "Breakfast"
          }
        ]
      },
      {
        "name": "Snack Stocking",
        "items": [
          {
            "name": "Hummus",
            "qty": "1 tub",
            "for": ""
          },
          {
            "name": "Carrots, cucumber, bell pepper strips",
            "qty": "assorted",
            "for": ""
          },
          {
            "name": "String cheese (pasteurized)",
            "qty": "1 pack",
            "for": ""
          },
          {
            "name": "Whole grain crackers",
            "qty": "1 box",
            "for": ""
          },
          {
            "name": "Almonds",
            "qty": "1 lb",
            "for": ""
          },
          {
            "name": "Dried apricots",
            "qty": "1 bag",
            "for": "Iron snack"
          }
        ]
      }
    ]
  },
  {
    "week": 2,
    "dateLabel": "Sun May 3 - Sat May 9",
    "sections": [
      {
        "name": "Proteins",
        "items": [
          {
            "name": "Ground turkey (93/7)",
            "qty": "2.5 lb",
            "for": "Stuffed peppers Sun + Skillet Mon"
          },
          {
            "name": "Salmon fillets (6 oz each)",
            "qty": "4",
            "for": "Tuesday sheet pan"
          },
          {
            "name": "Chuck roast",
            "qty": "3.5 lb",
            "for": "Wed Instant Pot, uses into Thu barbacoa"
          },
          {
            "name": "Chicken breast or thighs",
            "qty": "1.5 lb",
            "for": "Fri dump soup"
          },
          {
            "name": "Bone-in skin-on chicken thighs",
            "qty": "8",
            "for": "Sat Greek chicken"
          }
        ]
      },
      {
        "name": "Produce",
        "items": [
          {
            "name": "Large bell peppers",
            "qty": "5",
            "for": "Stuffed peppers Sun"
          },
          {
            "name": "Bell peppers for other uses",
            "qty": "3",
            "for": "Fajitas pantry stocker / skillet"
          },
          {
            "name": "Yellow onions",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Carrots",
            "qty": "6",
            "for": "Dump soup + snacks"
          },
          {
            "name": "Celery",
            "qty": "1 bunch",
            "for": "Dump soup + snacks"
          },
          {
            "name": "Baby potatoes (gold or red)",
            "qty": "2.5 lb",
            "for": "Salmon + Greek chicken"
          },
          {
            "name": "Asparagus",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Lemons",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Limes",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Garlic head",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Baby spinach",
            "qty": "10 oz",
            "for": "Dump soup + wraps"
          },
          {
            "name": "Fresh parsley",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Fresh dill",
            "qty": "small bunch",
            "for": "Salmon"
          },
          {
            "name": "Avocados",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Roma tomatoes",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Cilantro",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Cucumber",
            "qty": "1",
            "for": "Cottage cheese bowls"
          },
          {
            "name": "Apples",
            "qty": "3",
            "for": "Snacks"
          },
          {
            "name": "Bananas",
            "qty": "6",
            "for": "Smoothies + overnight oats"
          },
          {
            "name": "Cherry tomatoes",
            "qty": "1 pint",
            "for": "Power bowl Sun + cobb jar Sat"
          },
          {
            "name": "Romaine",
            "qty": "1 head",
            "for": "Cobb jar"
          }
        ]
      },
      {
        "name": "Dairy / Refrigerated",
        "items": [
          {
            "name": "Shredded cheddar",
            "qty": "8 oz",
            "for": ""
          },
          {
            "name": "Feta (pasteurized)",
            "qty": "6 oz",
            "for": "Greek chicken"
          },
          {
            "name": "Mozzarella (shredded, pasteurized)",
            "qty": "8 oz",
            "for": "Stuffed peppers"
          },
          {
            "name": "Parmesan (grated, pasteurized)",
            "qty": "small tub",
            "for": ""
          },
          {
            "name": "Greek yogurt (full fat)",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Cottage cheese",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Whole milk",
            "qty": "1/2 gal",
            "for": ""
          },
          {
            "name": "Large eggs",
            "qty": "2 dozen",
            "for": "Egg muffins Fri/Sat + breakfast burritos prep"
          },
          {
            "name": "Pepperoncini",
            "qty": "1 jar",
            "for": "Mississippi pot roast"
          },
          {
            "name": "Butter",
            "qty": "1 stick",
            "for": "Pot roast"
          }
        ]
      },
      {
        "name": "Pantry / Dry",
        "items": [
          {
            "name": "Quinoa",
            "qty": "1 cup (dry)",
            "for": "Stuffed peppers"
          },
          {
            "name": "Rice (jasmine or long grain)",
            "qty": "2 cups (dry)",
            "for": "Skillet + barbacoa night"
          },
          {
            "name": "Orzo or rice for soup",
            "qty": "1 cup",
            "for": ""
          },
          {
            "name": "Ranch seasoning packet",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Au jus gravy mix",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Fire roasted diced tomatoes",
            "qty": "2 cans",
            "for": ""
          },
          {
            "name": "Diced tomatoes with green chiles",
            "qty": "1 can",
            "for": ""
          },
          {
            "name": "Cannellini or white beans",
            "qty": "1 can",
            "for": "Dump soup"
          },
          {
            "name": "Taco seasoning",
            "qty": "2 tbsp equivalent",
            "for": ""
          },
          {
            "name": "Black beans",
            "qty": "2 cans",
            "for": ""
          },
          {
            "name": "Kalamata olives",
            "qty": "1 small jar",
            "for": "Greek chicken"
          },
          {
            "name": "Small corn tortillas",
            "qty": "1 pack",
            "for": "Barbacoa tacos"
          },
          {
            "name": "Marinara sauce",
            "qty": "16 oz",
            "for": "Stuffed peppers"
          },
          {
            "name": "Beef broth",
            "qty": "16 oz",
            "for": "Pot roast"
          },
          {
            "name": "Chipotle in adobo",
            "qty": "1 small can",
            "for": "Barbacoa tacos Thu"
          },
          {
            "name": "Queso fresco or cotija (pasteurized)",
            "qty": "6 oz",
            "for": "Barbacoa tacos topping"
          },
          {
            "name": "Pumpkin seeds",
            "qty": "small bag",
            "for": "Power bowl Sun"
          },
          {
            "name": "Sour cream (or Greek yogurt sub)",
            "qty": "8 oz",
            "for": "Tacos + skillet topping"
          }
        ]
      },
      {
        "name": "Breakfast Restock",
        "items": [
          {
            "name": "Rolled oats",
            "qty": "restock if low",
            "for": "Overnight oats Sun/Mon"
          },
          {
            "name": "Chia seeds",
            "qty": "restock if low",
            "for": "Overnight oats"
          },
          {
            "name": "Granola",
            "qty": "1 bag",
            "for": "Yogurt parfait Tue"
          },
          {
            "name": "Peanut butter",
            "qty": "restock if low",
            "for": "Overnight oats + smoothie"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "restock if low",
            "for": "Smoothie + overnight oats"
          },
          {
            "name": "Large flour tortillas (burrito size)",
            "qty": "6",
            "for": "Breakfast burritos prep"
          },
          {
            "name": "Breakfast sausage or chorizo",
            "qty": "8 oz",
            "for": "Breakfast burritos"
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "16 oz jar",
            "for": "Burritos + Mon taco skillet + Thu barbacoa tacos"
          }
        ]
      },
      {
        "name": "Frozen / Misc",
        "items": [
          {
            "name": "Frozen corn",
            "qty": "1 bag",
            "for": "Skillet"
          },
          {
            "name": "Frozen berries",
            "qty": "1 bag",
            "for": "Breakfast"
          },
          {
            "name": "Green beans (fresh or frozen)",
            "qty": "1 lb",
            "for": "Pot roast side"
          }
        ]
      },
      {
        "name": "Snack Restock",
        "items": [
          {
            "name": "Hard boiled eggs",
            "qty": "restock every Sunday",
            "for": ""
          },
          {
            "name": "Edamame (shelled frozen)",
            "qty": "1 bag",
            "for": ""
          },
          {
            "name": "Roasted chickpeas or make own",
            "qty": "1 bag",
            "for": ""
          }
        ]
      }
    ]
  },
  {
    "week": 3,
    "dateLabel": "Sun May 10 - Sat May 16",
    "sections": [
      {
        "name": "Proteins",
        "items": [
          {
            "name": "Boneless pork shoulder",
            "qty": "3.5 lb",
            "for": "Instant Pot pulled pork Sun"
          },
          {
            "name": "Chicken cutlets or breasts",
            "qty": "2 lb",
            "for": "Air fryer chicken parm Tue"
          },
          {
            "name": "Ground turkey (93/7)",
            "qty": "1 lb",
            "for": "Italian wedding soup"
          },
          {
            "name": "Chicken breast",
            "qty": "1 lb",
            "for": "Sheet pan fajitas Thu"
          },
          {
            "name": "Large shrimp (peeled deveined)",
            "qty": "1 lb",
            "for": "Fri skillet"
          },
          {
            "name": "Fully cooked andouille or chicken sausage",
            "qty": "12 oz",
            "for": "Fri skillet"
          }
        ]
      },
      {
        "name": "Produce",
        "items": [
          {
            "name": "Cabbage or bagged coleslaw mix",
            "qty": "1",
            "for": "Sandwich slaw"
          },
          {
            "name": "Bell peppers mixed",
            "qty": "4",
            "for": "Fajitas + skillet"
          },
          {
            "name": "Red onion",
            "qty": "1 large",
            "for": ""
          },
          {
            "name": "Yellow onions",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Carrots",
            "qty": "3",
            "for": "Wedding soup"
          },
          {
            "name": "Celery",
            "qty": "3 stalks",
            "for": "Wedding soup"
          },
          {
            "name": "Limes",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Lemons",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Garlic head",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Baby spinach or escarole",
            "qty": "12 oz",
            "for": "Wedding soup + smoothie + egg muffins"
          },
          {
            "name": "Romaine or cabbage",
            "qty": "1 head",
            "for": "Carnitas bowl slaw"
          },
          {
            "name": "Cherry tomatoes",
            "qty": "1 pint",
            "for": "Power bowls, cobb jars"
          },
          {
            "name": "Cucumber",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Avocados",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Fresh basil",
            "qty": "1 package",
            "for": ""
          },
          {
            "name": "Fresh parsley",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Green onions",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Oranges",
            "qty": "2",
            "for": "Carnitas glaze + snack"
          },
          {
            "name": "Bananas",
            "qty": "6",
            "for": "Smoothies + oats"
          }
        ]
      },
      {
        "name": "Dairy / Refrigerated",
        "items": [
          {
            "name": "Mozzarella (shredded)",
            "qty": "8 oz",
            "for": "Chicken parm"
          },
          {
            "name": "Parmesan (grated)",
            "qty": "restock",
            "for": ""
          },
          {
            "name": "Greek yogurt",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Cottage cheese",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Whole milk",
            "qty": "1/2 gal",
            "for": ""
          },
          {
            "name": "Large eggs",
            "qty": "2 dozen",
            "for": "Egg muffins Fri/Sat + breakfast burritos"
          },
          {
            "name": "Monterey Jack shredded",
            "qty": "8 oz",
            "for": ""
          },
          {
            "name": "Mayo",
            "qty": "small jar",
            "for": "Slaw"
          },
          {
            "name": "Queso fresco (pasteurized)",
            "qty": "4 oz",
            "for": "Carnitas bowl topping"
          },
          {
            "name": "Hummus",
            "qty": "1 tub",
            "for": "Wrap Fri + snacks"
          },
          {
            "name": "Feta (pasteurized)",
            "qty": "4 oz",
            "for": "Wrap Fri"
          }
        ]
      },
      {
        "name": "Pantry / Dry",
        "items": [
          {
            "name": "Brioche buns or hamburger buns",
            "qty": "6",
            "for": ""
          },
          {
            "name": "Rigatoni or penne",
            "qty": "12 oz",
            "for": "Meatball pasta next week prep"
          },
          {
            "name": "Whole wheat pasta for chicken parm",
            "qty": "12 oz",
            "for": ""
          },
          {
            "name": "Acini de pepe or orzo",
            "qty": "1 cup",
            "for": "Wedding soup"
          },
          {
            "name": "BBQ sauce",
            "qty": "18 oz",
            "for": ""
          },
          {
            "name": "Apple cider vinegar",
            "qty": "small bottle",
            "for": ""
          },
          {
            "name": "Brown sugar",
            "qty": "small bag",
            "for": ""
          },
          {
            "name": "Chicken broth",
            "qty": "64 oz",
            "for": "Wedding soup + pork"
          },
          {
            "name": "Diced tomatoes",
            "qty": "1 can",
            "for": "Skillet"
          },
          {
            "name": "Panko",
            "qty": "restock",
            "for": ""
          },
          {
            "name": "Marinara sauce",
            "qty": "24 oz",
            "for": "Chicken parm"
          },
          {
            "name": "Flour and breadcrumb basics",
            "qty": "as needed",
            "for": "Chicken parm"
          },
          {
            "name": "Fajita seasoning or DIY mix",
            "qty": "2 tbsp",
            "for": ""
          },
          {
            "name": "Flour tortillas",
            "qty": "1 pack",
            "for": "Fajitas"
          },
          {
            "name": "Cajun seasoning",
            "qty": "small jar",
            "for": "Skillet"
          },
          {
            "name": "Cilantro lime rice base",
            "qty": "2 cups cooked",
            "for": "Carnitas bowls"
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "16 oz jar",
            "for": "Carnitas bowls Mon + fajitas Thu + skillet Fri"
          },
          {
            "name": "Red lentils",
            "qty": "1.5 cups dry",
            "for": "Red lentil soup Sat"
          },
          {
            "name": "Tomato paste",
            "qty": "small can or tube",
            "for": "Red lentil soup"
          },
          {
            "name": "Black beans (canned)",
            "qty": "2 cans",
            "for": "Carnitas bowls Mon + power bowl Sun"
          },
          {
            "name": "Chickpeas (canned)",
            "qty": "1 can",
            "for": "Cobb jar + power bowl"
          },
          {
            "name": "Sour cream",
            "qty": "8 oz",
            "for": "Fajitas Thu + carnitas bowls"
          }
        ]
      },
      {
        "name": "Breakfast Restock",
        "items": [
          {
            "name": "Rolled oats",
            "qty": "restock if low",
            "for": "Overnight oats Sun/Mon"
          },
          {
            "name": "Chia seeds",
            "qty": "restock if low",
            "for": "Overnight oats"
          },
          {
            "name": "Granola",
            "qty": "1 bag",
            "for": "Yogurt parfait Tue"
          },
          {
            "name": "Peanut butter",
            "qty": "restock if low",
            "for": "Overnight oats + smoothie"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "restock if low",
            "for": "Smoothie + overnight oats"
          },
          {
            "name": "Large flour tortillas (burrito size)",
            "qty": "6",
            "for": "Breakfast burritos"
          }
        ]
      },
      {
        "name": "Frozen / Misc",
        "items": [
          {
            "name": "Frozen berries",
            "qty": "restock",
            "for": ""
          }
        ]
      }
    ]
  },
  {
    "week": 4,
    "dateLabel": "Sun May 17 - Sat May 23",
    "sections": [
      {
        "name": "Proteins",
        "items": [
          {
            "name": "Boneless skinless chicken thighs",
            "qty": "3 lb",
            "for": "Instant Pot shredded chicken Sun"
          },
          {
            "name": "Ground turkey",
            "qty": "3 lb",
            "for": "Meatballs Wed + second stuffed peppers Fri"
          },
          {
            "name": "Beef stew meat",
            "qty": "1.5 lb",
            "for": "Thu beef and barley soup"
          },
          {
            "name": "Salmon fillets",
            "qty": "4 (6 oz)",
            "for": "Sat second salmon"
          }
        ]
      },
      {
        "name": "Produce",
        "items": [
          {
            "name": "Sweet potatoes medium",
            "qty": "4",
            "for": "Buffalo stuffed sweet potatoes"
          },
          {
            "name": "Bell peppers",
            "qty": "4",
            "for": "Enchilada skillet + stuffed peppers"
          },
          {
            "name": "Large bell peppers",
            "qty": "5",
            "for": "Stuffed peppers"
          },
          {
            "name": "Yellow onions",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Red onion",
            "qty": "1",
            "for": "Fajitas pantry"
          },
          {
            "name": "Carrots",
            "qty": "4",
            "for": "Soup"
          },
          {
            "name": "Celery",
            "qty": "4 stalks",
            "for": "Buffalo sweet potatoes, snacks"
          },
          {
            "name": "Mushrooms",
            "qty": "8 oz",
            "for": "Beef barley"
          },
          {
            "name": "Kale or spinach",
            "qty": "2 bunches",
            "for": "Soup + stuffed peppers"
          },
          {
            "name": "Baby potatoes",
            "qty": "1.5 lb",
            "for": "Salmon"
          },
          {
            "name": "Asparagus",
            "qty": "1 bunch",
            "for": "Salmon"
          },
          {
            "name": "Lemons",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Limes",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Garlic head",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Cilantro",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Green onions",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Fresh parsley",
            "qty": "1 bunch",
            "for": "Soup finish"
          },
          {
            "name": "Fresh dill",
            "qty": "small bunch",
            "for": "Salmon"
          },
          {
            "name": "Avocados",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Roma tomatoes",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Apples",
            "qty": "3",
            "for": "Snacks"
          },
          {
            "name": "Bananas",
            "qty": "6",
            "for": "Smoothies"
          }
        ]
      },
      {
        "name": "Dairy / Refrigerated",
        "items": [
          {
            "name": "Plain Greek yogurt",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Cottage cheese",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Crumbled blue cheese or feta (pasteurized)",
            "qty": "4 oz",
            "for": "Buffalo sweet potatoes"
          },
          {
            "name": "Shredded Monterey Jack",
            "qty": "8 oz",
            "for": "Enchilada skillet"
          },
          {
            "name": "Mozzarella shredded",
            "qty": "8 oz",
            "for": "Stuffed peppers"
          },
          {
            "name": "Parmesan",
            "qty": "restock",
            "for": ""
          },
          {
            "name": "Ranch seasoning packet",
            "qty": "1 if not on hand",
            "for": ""
          },
          {
            "name": "Whole milk",
            "qty": "1/2 gal",
            "for": ""
          },
          {
            "name": "Large eggs",
            "qty": "2 dozen",
            "for": "Egg muffins Fri/Sat + breakfast burritos"
          },
          {
            "name": "Butter",
            "qty": "1 stick",
            "for": "Buffalo sweet potatoes Mon"
          },
          {
            "name": "Queso fresco (pasteurized)",
            "qty": "6 oz",
            "for": "Tacos Sun"
          },
          {
            "name": "Sour cream",
            "qty": "8 oz",
            "for": "Tacos + skillet topping"
          }
        ]
      },
      {
        "name": "Produce extras",
        "items": [
          {
            "name": "Fresh basil",
            "qty": "1 package",
            "for": "Turkey meatballs Wed"
          },
          {
            "name": "Cherry tomatoes",
            "qty": "1 pint",
            "for": "Power bowl Sun + cobb jar Sat"
          },
          {
            "name": "Romaine",
            "qty": "1 head",
            "for": "Cobb jar"
          }
        ]
      },
      {
        "name": "Pantry / Dry",
        "items": [
          {
            "name": "Pearl barley",
            "qty": "1 cup",
            "for": "Soup"
          },
          {
            "name": "Quinoa",
            "qty": "restock",
            "for": "Stuffed peppers"
          },
          {
            "name": "Rigatoni or penne",
            "qty": "12 oz",
            "for": "Meatball pasta"
          },
          {
            "name": "Small corn tortillas",
            "qty": "1 pack",
            "for": "Shredded chicken tacos"
          },
          {
            "name": "Frank's RedHot",
            "qty": "1 bottle",
            "for": ""
          },
          {
            "name": "Red enchilada sauce",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Fire roasted diced tomatoes",
            "qty": "1 can",
            "for": ""
          },
          {
            "name": "Beef broth",
            "qty": "48 oz",
            "for": "Beef barley"
          },
          {
            "name": "Chicken broth",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Worcestershire sauce",
            "qty": "small bottle",
            "for": ""
          },
          {
            "name": "Black beans",
            "qty": "1 can",
            "for": ""
          },
          {
            "name": "Marinara",
            "qty": "24 oz",
            "for": "Meatballs + stuffed peppers"
          },
          {
            "name": "Bay leaves, thyme",
            "qty": "as needed",
            "for": ""
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "16 oz jar",
            "for": "Shredded chicken tacos Sun + enchilada skillet Tue"
          },
          {
            "name": "Panko breadcrumbs",
            "qty": "small box",
            "for": "Turkey meatballs Wed"
          },
          {
            "name": "Tomato paste",
            "qty": "small can or tube",
            "for": "Beef and barley soup Thu"
          }
        ]
      },
      {
        "name": "Breakfast Restock",
        "items": [
          {
            "name": "Rolled oats",
            "qty": "restock if low",
            "for": "Overnight oats Sun/Mon"
          },
          {
            "name": "Chia seeds",
            "qty": "restock if low",
            "for": "Overnight oats"
          },
          {
            "name": "Granola",
            "qty": "1 bag",
            "for": "Yogurt parfait Tue"
          },
          {
            "name": "Peanut butter",
            "qty": "restock if low",
            "for": "Overnight oats + smoothie"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "restock if low",
            "for": "Smoothie + overnight oats"
          },
          {
            "name": "Large flour tortillas (burrito size)",
            "qty": "6",
            "for": "Breakfast burritos"
          },
          {
            "name": "Baby spinach",
            "qty": "8 oz",
            "for": "Smoothie + egg muffins"
          }
        ]
      },
      {
        "name": "Frozen / Misc",
        "items": [
          {
            "name": "Frozen corn",
            "qty": "1 bag",
            "for": ""
          },
          {
            "name": "Frozen berries",
            "qty": "restock",
            "for": ""
          }
        ]
      }
    ]
  },
  {
    "week": 5,
    "dateLabel": "Sun May 24 - Sun May 31 (8 days)",
    "sections": [
      {
        "name": "Proteins",
        "items": [
          {
            "name": "Boneless pork shoulder",
            "qty": "3.5 lb",
            "for": "Instant Pot pulled pork Sun"
          },
          {
            "name": "Fully cooked chicken Italian sausage",
            "qty": "12 oz",
            "for": "White bean soup"
          },
          {
            "name": "Ground turkey",
            "qty": "1.25 lb",
            "for": "Wed taco skillet"
          },
          {
            "name": "Chicken breast",
            "qty": "1 lb",
            "for": "Fajitas Thu"
          },
          {
            "name": "Chicken cutlets",
            "qty": "2 lb",
            "for": "Chicken parm Fri"
          },
          {
            "name": "Chicken breast for tortilla soup",
            "qty": "1.25 lb",
            "for": "Sat"
          },
          {
            "name": "Bone-in skin-on chicken thighs",
            "qty": "8",
            "for": "Sun May 31 close out"
          }
        ]
      },
      {
        "name": "Produce",
        "items": [
          {
            "name": "Cabbage or coleslaw mix",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Bell peppers",
            "qty": "5",
            "for": "Fajitas, skillet, tortilla soup"
          },
          {
            "name": "Yellow onions",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Red onion",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Carrots",
            "qty": "3",
            "for": "Snacks"
          },
          {
            "name": "Celery",
            "qty": "3 stalks",
            "for": "Soup"
          },
          {
            "name": "Kale (lacinato)",
            "qty": "1 bunch",
            "for": "White bean soup"
          },
          {
            "name": "Baby gold potatoes",
            "qty": "1.5 lb",
            "for": "Sun 31 Greek chicken"
          },
          {
            "name": "Lemons",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Limes",
            "qty": "3",
            "for": ""
          },
          {
            "name": "Garlic head",
            "qty": "1",
            "for": ""
          },
          {
            "name": "Cilantro",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Fresh parsley",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Green onions",
            "qty": "1 bunch",
            "for": ""
          },
          {
            "name": "Avocados",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Roma tomatoes",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Cherry tomatoes",
            "qty": "1 pint",
            "for": "Bowls"
          },
          {
            "name": "Cucumber",
            "qty": "2",
            "for": ""
          },
          {
            "name": "Oranges",
            "qty": "2",
            "for": "Carnitas"
          },
          {
            "name": "Romaine",
            "qty": "1 head",
            "for": "Slaw + salads"
          },
          {
            "name": "Apples",
            "qty": "3",
            "for": "Snacks"
          },
          {
            "name": "Bananas",
            "qty": "6",
            "for": "Smoothies"
          }
        ]
      },
      {
        "name": "Dairy / Refrigerated",
        "items": [
          {
            "name": "Mozzarella shredded",
            "qty": "8 oz",
            "for": "Chicken parm"
          },
          {
            "name": "Parmesan",
            "qty": "restock",
            "for": ""
          },
          {
            "name": "Greek yogurt",
            "qty": "32 oz",
            "for": ""
          },
          {
            "name": "Cottage cheese",
            "qty": "16 oz",
            "for": ""
          },
          {
            "name": "Whole milk",
            "qty": "1/2 gal",
            "for": ""
          },
          {
            "name": "Large eggs",
            "qty": "2 dozen",
            "for": "Egg muffins Fri/Sat + breakfast burritos prep"
          },
          {
            "name": "Feta",
            "qty": "4 oz",
            "for": "Wraps"
          },
          {
            "name": "Shredded Monterey Jack",
            "qty": "8 oz",
            "for": "Tortilla soup"
          },
          {
            "name": "Mayo",
            "qty": "restock",
            "for": ""
          },
          {
            "name": "Shredded cheddar",
            "qty": "8 oz",
            "for": "Taco skillet Wed"
          },
          {
            "name": "Queso fresco (pasteurized)",
            "qty": "4 oz",
            "for": "Carnitas bowl topping"
          },
          {
            "name": "Sour cream",
            "qty": "8 oz",
            "for": "Fajitas Thu + skillet Wed"
          },
          {
            "name": "Butter",
            "qty": "1 stick",
            "for": "Cooking + meatball pasta"
          }
        ]
      },
      {
        "name": "Produce extras",
        "items": [
          {
            "name": "Fresh basil",
            "qty": "1 package",
            "for": "Chicken parm Fri"
          },
          {
            "name": "Kalamata olives",
            "qty": "1 small jar",
            "for": "Greek chicken Sun May 31"
          }
        ]
      },
      {
        "name": "Pantry / Dry",
        "items": [
          {
            "name": "Brioche buns",
            "qty": "4",
            "for": ""
          },
          {
            "name": "Flour tortillas",
            "qty": "1 pack",
            "for": ""
          },
          {
            "name": "Small corn tortillas",
            "qty": "1 pack",
            "for": ""
          },
          {
            "name": "Whole wheat pasta",
            "qty": "12 oz",
            "for": "Chicken parm"
          },
          {
            "name": "Cilantro lime rice base",
            "qty": "2 cups cooked",
            "for": "Carnitas bowls"
          },
          {
            "name": "Cannellini beans",
            "qty": "2 cans",
            "for": "White bean soup"
          },
          {
            "name": "Black beans",
            "qty": "1 can",
            "for": "Tortilla soup"
          },
          {
            "name": "Corn (can)",
            "qty": "1",
            "for": "Tortilla soup"
          },
          {
            "name": "Green chiles (can)",
            "qty": "1",
            "for": "Tortilla soup"
          },
          {
            "name": "Fire roasted diced tomatoes",
            "qty": "1 can",
            "for": ""
          },
          {
            "name": "Diced tomatoes with green chiles",
            "qty": "1 can",
            "for": ""
          },
          {
            "name": "Chicken broth",
            "qty": "48 oz",
            "for": ""
          },
          {
            "name": "BBQ sauce",
            "qty": "restock if low",
            "for": ""
          },
          {
            "name": "Marinara",
            "qty": "24 oz",
            "for": ""
          },
          {
            "name": "Tortilla strips",
            "qty": "1 bag (or make from corn tortillas)",
            "for": ""
          },
          {
            "name": "Rice",
            "qty": "2 cups dry",
            "for": ""
          },
          {
            "name": "Salsa (jarred, medium)",
            "qty": "16 oz jar",
            "for": "Carnitas Mon + taco skillet Wed + fajitas Thu + tortilla soup Sat"
          },
          {
            "name": "Panko breadcrumbs",
            "qty": "small box",
            "for": "Chicken parm Fri"
          },
          {
            "name": "Flour",
            "qty": "small bag (if low)",
            "for": "Chicken parm dredge"
          },
          {
            "name": "Fajita seasoning or DIY mix",
            "qty": "2 tbsp equivalent",
            "for": "Fajitas Thu"
          },
          {
            "name": "Taco seasoning",
            "qty": "2 tbsp equivalent",
            "for": "Taco skillet Wed"
          },
          {
            "name": "Apple cider vinegar",
            "qty": "restock if low",
            "for": "Pulled pork + slaw"
          }
        ]
      },
      {
        "name": "Breakfast Restock",
        "items": [
          {
            "name": "Rolled oats",
            "qty": "restock if low",
            "for": "Overnight oats Sun/Mon/Sun"
          },
          {
            "name": "Chia seeds",
            "qty": "restock if low",
            "for": "Overnight oats"
          },
          {
            "name": "Granola",
            "qty": "1 bag",
            "for": "Yogurt parfait Tue"
          },
          {
            "name": "Peanut butter",
            "qty": "restock if low",
            "for": "Overnight oats + smoothie"
          },
          {
            "name": "Whey or plant protein powder",
            "qty": "restock if low",
            "for": "Smoothie + overnight oats"
          },
          {
            "name": "Large flour tortillas (burrito size)",
            "qty": "6",
            "for": "Breakfast burritos"
          },
          {
            "name": "Baby spinach",
            "qty": "8 oz",
            "for": "Smoothie + egg muffins"
          }
        ]
      },
      {
        "name": "Frozen / Misc",
        "items": [
          {
            "name": "Frozen corn",
            "qty": "1 bag",
            "for": "Skillet"
          },
          {
            "name": "Frozen berries",
            "qty": "restock",
            "for": ""
          }
        ]
      }
    ]
  }
];
