"""Fetch Unsplash images for every recipe and write data/images.ts.

Usage:
    python3 scripts/fetch_images.py           # fetch only missing entries
    python3 scripts/fetch_images.py --force   # refetch everything

Reads UNSPLASH_ACCESS_KEY from .env.local (or env var).
Requires `requests` (pip install requests).
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path

import requests


ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
RECIPES_TS = DATA_DIR / "recipes.ts"
IMAGES_TS = DATA_DIR / "images.ts"


def load_env() -> dict[str, str]:
    env_path = ROOT / ".env.local"
    env: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    env.update({k: v for k, v in os.environ.items() if k.startswith("UNSPLASH_")})
    return env


def load_recipes() -> list[dict]:
    raw = RECIPES_TS.read_text()
    m = re.search(r"=\s*(\[.*\]);", raw, re.S)
    if not m:
        raise RuntimeError("Could not parse data/recipes.ts")
    return json.loads(m.group(1))


def load_existing() -> dict[str, dict]:
    if not IMAGES_TS.exists():
        return {}
    raw = IMAGES_TS.read_text()
    m = re.search(r"=\s*(\{.*\})\s*;?\s*$", raw, re.S)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except Exception:
        return {}


CATEGORY_HINT = {
    "dinner": "dinner plate",
    "soup": "soup bowl",
    "breakfast": "breakfast",
    "lunch": "lunch bowl",
    "snack": "food",
}

# Manual query overrides for recipes that return no hits with the default query.
QUERY_OVERRIDES: dict[str, str] = {
    "mississippi-pot-roast": "pot roast beef",
    "power-protein-smoothie": "protein smoothie glass",
    "tuna-salad-on-whole-grain": "tuna salad sandwich",
    "sheet-pan-honey-soy-salmon": "glazed salmon broccoli",
}


def build_query(recipe: dict) -> str:
    override = QUERY_OVERRIDES.get(recipe["slug"])
    if override:
        return override
    name = recipe["name"].lower()
    name = re.sub(r"\breuses [^,]*", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    hint = CATEGORY_HINT.get(recipe["category"], "food")
    return f"{name} {hint}".strip()


def fetch_one(access_key: str, query: str) -> dict | None:
    resp = requests.get(
        "https://api.unsplash.com/search/photos",
        params={
            "query": query,
            "orientation": "landscape",
            "per_page": 1,
            "content_filter": "high",
        },
        headers={"Authorization": f"Client-ID {access_key}"},
        timeout=15,
    )
    if resp.status_code == 403:
        print("  rate limited (403). Sleeping 60s...")
        time.sleep(60)
        return fetch_one(access_key, query)
    resp.raise_for_status()
    data = resp.json()
    results = data.get("results") or []
    if not results:
        return None
    p = results[0]
    user = p.get("user") or {}
    urls = p.get("urls") or {}
    links = p.get("links") or {}
    user_links = user.get("links") or {}
    return {
        "url": urls.get("regular"),
        "smallUrl": urls.get("small"),
        "blurColor": p.get("color") or "#eadfcb",
        "alt": p.get("alt_description") or query,
        "attribution": {
            "name": user.get("name") or "Unsplash",
            "username": user.get("username") or "",
            "photoLink": links.get("html") or "",
            "userLink": user_links.get("html") or "",
        },
    }


def ts_literal(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False)


def main() -> None:
    force = "--force" in sys.argv
    env = load_env()
    key = env.get("UNSPLASH_ACCESS_KEY")
    if not key:
        print("UNSPLASH_ACCESS_KEY missing from .env.local")
        sys.exit(1)

    recipes = load_recipes()
    existing = {} if force else load_existing()
    out: dict[str, dict] = {**existing}

    missing = [r for r in recipes if r["slug"] not in out]
    print(f"Have {len(out)} existing, fetching {len(missing)} new.")

    for i, r in enumerate(missing, 1):
        q = build_query(r)
        print(f"  [{i}/{len(missing)}] {r['slug']}  <-  {q!r}")
        try:
            img = fetch_one(key, q)
        except Exception as e:
            print(f"    error: {e}")
            continue
        if img:
            out[r["slug"]] = img
        else:
            print("    no results")
        time.sleep(0.2)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    header = "// GENERATED by scripts/fetch_images.py. Do not edit by hand.\n"
    IMAGES_TS.write_text(
        header +
        'import type { RecipeImageData } from "./types";\n\n' +
        f"export const images: Record<string, RecipeImageData> = {ts_literal(out)};\n"
    )
    print(f"Wrote {len(out)} entries to data/images.ts")


if __name__ == "__main__":
    main()
